# Generated by Django 6.0.5 on 2026-05-29 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DawProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('emoji', models.CharField(default='🎛️', max_length=8)),
                ('color', models.CharField(default='#a855f7', max_length=9)),
                ('comparable_to', models.CharField(blank=True, default='', max_length=120)),
                ('tagline', models.CharField(blank=True, default='', max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('features', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('building', 'Building'), ('live', 'Live')], default='proposed', max_length=12)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DawVote',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='daw_vote', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='dawz.dawproposal')),
            ],
        ),
    ]
