# Generated by Django 6.0.9 on 2026-10-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_unique_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthidentity",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
