# Generated by Django 5.2.17 on 2026-09-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_unique_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("phone", "Phone")], max_length=10
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["identifier", "channel", "expires_at"],
                        name="accounts_ot_identif_0dc428_idx",
                    )
                ],
                "unique_together": {("identifier", "channel")},
            },
        ),
    ]
