services:
  - type: web
    name: music-connectz-python-backend
    runtime: python
    pythonVersion: 3.11
    plan: starter
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:10000 app:app
    envVars:
      - key: PORT
        value: 10000
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
