"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'dev-only-insecure-key-change-me'
    else:
        raise ValueError('SECRET_KEY environment variable is required when DEBUG=False')

ALLOWED_HOSTS = [
    "music-connectz-backend-1.onrender.com",
    "music-connectz-backend-2.onrender.com",
    "backend.musicconnectz.net",
    "admin.musicconnectz.net",
    "backend.musicconnectz.com",
    "admin.musicconnectz.com",
    "localhost",
    "127.0.0.1"
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'backend.apps.BackendConfig',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.apple',
    'allauth.socialaccount.providers.microsoft',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.instagram',
    'allauth.socialaccount.providers.twitter_oauth2',
    'allauth.socialaccount.providers.linkedin_oauth2',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.amazon',
    'allauth.socialaccount.providers.discogs',
    'allauth.socialaccount.providers.patreon',
    'allauth.socialaccount.providers.spotify',
    'allauth.socialaccount.providers.soundcloud',
    'allauth.socialaccount.providers.tiktok',
    'allauth.socialaccount.providers.twitch',
    'allauth.socialaccount.providers.spotify',
    'allauth.socialaccount.providers.soundcloud',
    'allauth.socialaccount.providers.tiktok',
    'rest_framework',
    'corsheaders',
]
# Add site id for django.contrib.sites
SITE_ID = 1

# Authentication backends for allauth
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_AUTHENTICATION_METHOD = "username_email"  # Allow login with username OR email
ACCOUNT_USERNAME_REQUIRED = False                  # Username is optional
ACCOUNT_EMAIL_REQUIRED = False                     # Email is optional
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_SIGNUP_FIELDS = ["username", "email", "password1", "password2"]
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_STORE_TOKENS = True
SOCIALACCOUNT_ADAPTER = 'backend.adapters.SafeSocialAccountAdapter'
OAUTH_CANONICAL_HOST = (os.environ.get('OAUTH_CANONICAL_HOST') or 'admin.musicconnectz.net').strip().lower()
OAUTH_CANONICAL_SCHEME = (os.environ.get('OAUTH_CANONICAL_SCHEME') or 'https').strip().lower()
OAUTH_CANONICAL_ENFORCE = (os.environ.get('OAUTH_CANONICAL_ENFORCE') or ('0' if DEBUG else '1')) == '1'
SOCIALACCOUNT_PROVIDERS = {
    'apple': {
        'SCOPE': ['name', 'email'],
    },
    'microsoft': {
        'SCOPE': ['openid', 'profile', 'email'],
    },
    'facebook': {
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'rerequest'},
    },
    'instagram': {},
    'twitter_oauth2': {
        'SCOPE': ['users.read', 'tweet.read', 'offline.access'],
    },
    'linkedin_oauth2': {
        'SCOPE': ['openid', 'profile', 'email'],
    },
    'github': {
        'SCOPE': ['read:user', 'user:email'],
    },
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'prompt': 'select_account'},
    },
    'amazon': {
        'SCOPE': ['profile'],
    },
    'discogs': {
        'SCOPE': ['identity'],
    },
    'patreon': {
        'SCOPE': ['identity'],
    },
    'spotify': {
        'SCOPE': ['user-read-email'],
    },
    'soundcloud': {
        'SCOPE': ['non-expiring'],
    },
    'tiktok': {
        'SCOPE': ['user.info.basic', 'user.info.profile'],
    },
    'twitch': {
        'SCOPE': ['user:read:email'],
    },
}


def _set_social_app_from_env(provider_key, client_id_env, client_secret_env, key_env=None, id_fallback_env=None):
    client_id = (os.environ.get(client_id_env) or '').strip()
    if not client_id and id_fallback_env:
        client_id = (os.environ.get(id_fallback_env) or '').strip()
    client_secret = (os.environ.get(client_secret_env) or '').strip()
    provider_key_value = (os.environ.get(key_env) or '').strip() if key_env else ''
    if client_id and client_secret:
        SOCIALACCOUNT_PROVIDERS.setdefault(provider_key, {})['APP'] = {
            'client_id': client_id,
            'secret': client_secret,
            'key': provider_key_value,
        }


_set_social_app_from_env('facebook', 'FACEBOOK_CLIENT_ID', 'FACEBOOK_CLIENT_SECRET')
_set_social_app_from_env('instagram', 'INSTAGRAM_CLIENT_ID', 'INSTAGRAM_CLIENT_SECRET', id_fallback_env='INSTAGRAM_APP_ID')
_set_social_app_from_env('github', 'GITHUB_CLIENT_ID', 'GITHUB_CLIENT_SECRET')
_set_social_app_from_env('google', 'GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET')
_set_social_app_from_env('amazon', 'AMAZON_CLIENT_ID', 'AMAZON_CLIENT_SECRET')
_set_social_app_from_env('discogs', 'DISCOGS_CLIENT_ID', 'DISCOGS_CLIENT_SECRET')
_set_social_app_from_env('linkedin_oauth2', 'LINKEDIN_CLIENT_ID', 'LINKEDIN_CLIENT_SECRET')
_set_social_app_from_env('microsoft', 'MICROSOFT_CLIENT_ID', 'MICROSOFT_CLIENT_SECRET')
_set_social_app_from_env('patreon', 'PATREON_CLIENT_ID', 'PATREON_CLIENT_SECRET')
_set_social_app_from_env('amazon', 'AMAZON_CLIENT_ID', 'AMAZON_CLIENT_SECRET')
_set_social_app_from_env('discogs', 'DISCOGS_CLIENT_ID', 'DISCOGS_CLIENT_SECRET')
_set_social_app_from_env('linkedin_oauth2', 'LINKEDIN_CLIENT_ID', 'LINKEDIN_CLIENT_SECRET')
_set_social_app_from_env('microsoft', 'MICROSOFT_CLIENT_ID', 'MICROSOFT_CLIENT_SECRET')
_set_social_app_from_env('patreon', 'PATREON_CLIENT_ID', 'PATREON_CLIENT_SECRET')
_set_social_app_from_env('spotify', 'SPOTIFY_CLIENT_ID', 'SPOTIFY_CLIENT_SECRET')
_set_social_app_from_env('soundcloud', 'SOUNDCLOUD_CLIENT_ID', 'SOUNDCLOUD_CLIENT_SECRET')
_set_social_app_from_env('twitter_oauth2', 'TWITTER_CLIENT_ID', 'TWITTER_CLIENT_SECRET')
_set_social_app_from_env('tiktok', 'TIKTOK_CLIENT_ID', 'TIKTOK_CLIENT_SECRET', id_fallback_env='TIKTOK_CLIENT_KEY')
_set_social_app_from_env('twitch', 'TWITCH_CLIENT_ID', 'TWITCH_CLIENT_SECRET')
_set_social_app_from_env('twitch', 'TWITCH_CLIENT_ID', 'TWITCH_CLIENT_SECRET')

LOGIN_REDIRECT_URL = 'https://musicconnectz.net/'
LOGOUT_REDIRECT_URL = 'https://musicconnectz.net/'
SOCIALACCOUNT_ERROR_URL = 'https://musicconnectz.net/?login_error=1'


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'backend.middleware.OAuthRouteFailSafeMiddleware',
    'backend.middleware.CanonicalOAuthHostMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

<<<<<<< HEAD
def _database_config_from_url(url):
    parsed = urlparse(url)
    scheme = (parsed.scheme or '').lower()
    if scheme in {'postgres', 'postgresql', 'pgsql'}:
        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': (parsed.path or '/').lstrip('/'),
            'USER': parsed.username or '',
            'PASSWORD': parsed.password or '',
            'HOST': parsed.hostname or '',
            'PORT': str(parsed.port or 5432),
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
            'OPTIONS': {
                'sslmode': os.environ.get('DB_SSLMODE', 'require'),
            },
        }
    return None


_database_url = (os.environ.get('DATABASE_URL') or '').strip()
_database_from_url = _database_config_from_url(_database_url) if _database_url else None

DATABASES = {
    'default': _database_from_url or {
=======
DATABASES = {
    'default': {
>>>>>>> dec631da98253f85bff28b8e054535819adb2224
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Email backend configuration for Gmail SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@musicconnectz.com')

STATIC_URL = 'static/'

# CORS settings for frontend
CORS_ALLOWED_ORIGINS = [
    "https://musicconnectz.com",
    "https://www.musicconnectz.com",
    "https://musicconnectz.net",
    "https://www.musicconnectz.net",
    "https://backend.musicconnectz.net",
    "https://admin.musicconnectz.net",
    "https://backend.musicconnectz.com",
    "https://admin.musicconnectz.com",
    "https://music-connectz-frontend.vercel.app",
    "https://music-connectz-backend-2.onrender.com"
]

# Allow all Vercel preview deployment URLs (*.vercel.app)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^https://[\w-]+\.vercel\.app$',
]

# --- Distribution Premium Features ---
# Set to False in dev/testing to grant all users premium features
DISTRIBUTION_PREMIUM_ENFORCED = (os.environ.get('DISTRIBUTION_PREMIUM_ENFORCED', '0' if DEBUG else '1').lower() not in {'0', 'false', 'no'})
# Set to False in dev/testing to bypass feature checkout/payment enforcement.
FEATURE_PAYMENTS_ENFORCED = (os.environ.get('FEATURE_PAYMENTS_ENFORCED', '0' if DEBUG else '1').lower() not in {'0', 'false', 'no'})

# Analytics features
ANALYTICS_ENABLED = True
STREAM_EVENT_TRACKING_ENABLED = (os.environ.get('STREAM_EVENT_TRACKING_ENABLED', 'true').lower() != 'false')
CONTRIBUTOR_EARNINGS_TRACKING_ENABLED = True

CSRF_TRUSTED_ORIGINS = [
    "https://musicconnectz.com",
    "https://www.musicconnectz.com",
    "https://musicconnectz.net",
    "https://www.musicconnectz.net",
    "https://backend.musicconnectz.net",
    "https://admin.musicconnectz.net",
    "https://backend.musicconnectz.com",
    "https://admin.musicconnectz.com",
    "https://music-connectz-frontend.vercel.app",
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# --- Security Headers for Safer Site ---
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_SSL_REDIRECT = not DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_COOKIE_SECURE = True
<<<<<<< HEAD
CSRF_COOKIE_HTTPONLY = (os.environ.get('CSRF_COOKIE_HTTPONLY', '0' if DEBUG else '1').lower() not in {'0', 'false', 'no'})
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG
=======
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = True
>>>>>>> dec631da98253f85bff28b8e054535819adb2224
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
