# Generated by Django 6.0.5 on 2026-05-29 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('prompt', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('quiz', 'Quiz'), ('practice', 'Practice'), ('recording', 'Recording'), ('freeform', 'Freeform'), ('challenge', 'Challenge')], default='practice', max_length=12)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('xp_reward', models.PositiveIntegerField(default=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['track', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillz_attempts', to=settings.AUTH_USER_MODEL)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='skillz.drill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_key', models.CharField(db_index=True, max_length=32)),
                ('key', models.SlugField(max_length=64)),
                ('title', models.CharField(max_length=120)),
                ('persona_skill', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('emoji', models.CharField(blank=True, default='🎯', max_length=8)),
                ('color', models.CharField(blank=True, default='#a855f7', max_length=9)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['app_key', 'order'],
                'unique_together': {('app_key', 'key')},
            },
        ),
        migrations.AddField(
            model_name='drill',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drillz', to='skillz.skilltrack'),
        ),
        migrations.CreateModel(
            name='SkillProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('last_practiced', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillz_progress', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='skillz.skilltrack')),
            ],
            options={
                'unique_together': {('user', 'track')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=48)),
                ('app_key', models.CharField(blank=True, default='', max_length=32)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillz_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'code', 'app_key')},
            },
        ),
    ]
