# Generated by Django 5.2.15 on 2026-06-30 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(db_index=True, max_length=40)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=240)),
                ('icon', models.CharField(blank=True, default='', max_length=80)),
                ('rule', models.CharField(choices=[('xp', 'Total XP'), ('streak', 'Day streak'), ('drills', 'Drills completed')], default='xp', max_length=12)),
                ('threshold', models.PositiveIntegerField(default=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('app_key', 'order', 'threshold'),
                'unique_together': {('app_key', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(db_index=True, max_length=40)),
                ('key', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('xp', models.PositiveIntegerField(default=50)),
                ('icon', models.CharField(blank=True, default='', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('app_key', 'order', 'id'),
                'unique_together': {('app_key', 'key')},
            },
        ),
        migrations.CreateModel(
            name='TrainingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(db_index=True, max_length=40)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_active', models.DateField(blank=True, null=True)),
                ('drills_completed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-xp', '-current_streak'),
            },
        ),
        migrations.CreateModel(
            name='TrainingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drill_key', models.CharField(max_length=80)),
                ('score', models.PositiveIntegerField(default=0)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='skillz.trainingprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EarnedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='skillz.badge')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='skillz.trainingprofile')),
            ],
            options={
                'ordering': ('-earned_at',),
            },
        ),
        migrations.AddIndex(
            model_name='trainingprofile',
            index=models.Index(fields=['app_key', '-xp'], name='skillz_trai_app_key_feceeb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingprofile',
            unique_together={('user', 'app_key')},
        ),
        migrations.AlterUniqueTogether(
            name='earnedbadge',
            unique_together={('profile', 'badge')},
        ),
    ]
