# Generated by Django 6.0.6 on 2026-06-05 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_key', models.CharField(db_index=True, max_length=32)),
                ('source', models.CharField(choices=[('editor', 'Edited in-app'), ('import', 'Imported'), ('asset', 'From asset')], default='editor', max_length=8)),
                ('artifact_url', models.URLField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissionz', to='skillz.drill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillz_submissionz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
