# Generated by Django 5.2.16 on 2026-08-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangaz", "0002_mangaz_format_mangaz_runtime_seconds_meet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="art_source",
            field=models.CharField(
                choices=[
                    ("human", "Written by hand"),
                    ("script", "AI from an inserted script"),
                    ("character", "AI from character bio and MBTI"),
                ],
                default="human",
                max_length=12,
            ),
        ),
    ]
