# Generated by Django 5.2.16 on 2026-08-02 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangaz", "0003_page_art_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brief", models.TextField(blank=True, default="")),
                ("hours", models.PositiveIntegerField(default=1)),
                ("rate_cents", models.PositiveIntegerField(default=0)),
                ("paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mangaz_commissions_bought",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "designer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mangaz_commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commissions",
                        to="mangaz.mangaz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Volume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(blank=True, default="", max_length=160)),
                ("first_page", models.PositiveIntegerField(default=1)),
                ("last_page", models.PositiveIntegerField(default=1)),
                ("price_cents", models.PositiveIntegerField(default=0)),
                ("pass_price_cents", models.PositiveIntegerField(default=0)),
                ("pass_hours", models.PositiveIntegerField(default=48)),
                ("published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volumes",
                        to="mangaz.mangaz",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("manga", "number")},
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("own", "Buy it"),
                            ("pass", "Reading pass"),
                            ("commission", "Commission"),
                        ],
                        default="own",
                        max_length=12,
                    ),
                ),
                ("price_cents", models.PositiveIntegerField(default=0)),
                ("dev_tax_cents", models.PositiveIntegerField(default=0)),
                ("ai_royalty_cents", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mangaz_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="mangaz.volume",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
