# Generated by Django 5.2.16 on 2026-08-02 21:41

import apps.mangaz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangaz", "0004_commission_volume_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="art",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.mangaz.models.page_art_path
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="art_source",
            field=models.CharField(
                choices=[
                    ("human", "Made by hand"),
                    ("drawn", "Drawn in the app"),
                    ("upload", "Uploaded"),
                    ("script", "AI from an inserted script"),
                    ("character", "AI from character bio and MBTI"),
                ],
                default="human",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="source",
            field=models.CharField(
                choices=[
                    ("human", "Made by hand"),
                    ("drawn", "Drawn in the app"),
                    ("upload", "Uploaded"),
                    ("script", "AI from an inserted script"),
                    ("character", "AI from character bio and MBTI"),
                ],
                default="human",
                max_length=12,
            ),
        ),
    ]
