# Generated by Django 5.2.16 on 2026-08-02 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangaz", "0005_page_art_alter_page_art_source_alter_page_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="mangaz",
            name="reading_order",
            field=models.CharField(default="rtl", max_length=3),
        ),
        migrations.CreateModel(
            name="Balloon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("speech", "Speech"),
                            ("thought", "Thought"),
                            ("shout", "Shout"),
                            ("whisper", "Whisper"),
                            ("caption", "Caption"),
                            ("sfx", "Sound effect"),
                        ],
                        default="speech",
                        max_length=10,
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("x", models.FloatField(default=10)),
                ("y", models.FloatField(default=10)),
                ("width", models.FloatField(default=25)),
                ("height", models.FloatField(default=15)),
                ("tail_x", models.FloatField(blank=True, null=True)),
                ("tail_y", models.FloatField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=1)),
                ("font_scale", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balloons",
                        to="mangaz.page",
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="balloons",
                        to="mangaz.characterz",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
