# Generated by Django 5.2.16 on 2026-08-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangaz", "0006_mangaz_reading_order_balloon"),
    ]

    operations = [
        migrations.AddField(
            model_name="balloon",
            name="translations",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
