# Generated by Django 6.0.3 on 2026-04-03 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_userprofile_profile_fields_authauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('version_title', models.CharField(blank=True, default='', max_length=255)),
                ('primary_artist', models.CharField(max_length=255)),
                ('release_type', models.CharField(choices=[('single', 'Single'), ('ep', 'EP'), ('album', 'Album')], default='single', max_length=16)),
                ('genre', models.CharField(blank=True, default='', max_length=128)),
                ('language', models.CharField(blank=True, default='en', max_length=32)),
                ('explicit', models.BooleanField(default=False)),
                ('upc', models.CharField(blank=True, default='', max_length=32)),
                ('planned_release_date', models.DateField(blank=True, null=True)),
                ('original_release_date', models.DateField(blank=True, null=True)),
                ('cover_art_file', models.FileField(blank=True, null=True, upload_to='distribution/covers/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('provider_release_id', models.CharField(blank=True, default='', max_length=255)),
                ('validation_errors_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('operation', models.CharField(max_length=32)),
                ('request_payload_json', models.JSONField(blank=True, default=dict)),
                ('response_payload_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_jobs', to='backend.release')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('event_type', models.CharField(max_length=64)),
                ('event_time', models.DateTimeField()),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_events', to='backend.release')),
            ],
            options={
                'ordering': ['-event_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('featured_artists', models.CharField(blank=True, default='', max_length=255)),
                ('isrc', models.CharField(blank=True, default='', max_length=32)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='distribution/audio/')),
                ('explicit', models.BooleanField(default=False)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('composer_writers_json', models.JSONField(blank=True, default=list)),
                ('publisher_info_json', models.JSONField(blank=True, default=dict)),
                ('lyrics_text', models.TextField(blank=True, default='')),
                ('language', models.CharField(blank=True, default='en', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='backend.release')),
            ],
            options={
                'ordering': ['sequence_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DistributionAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ditto', 'Ditto'), ('generic_partner', 'Generic Partner')], max_length=32)),
                ('external_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('disconnected', 'Disconnected')], default='pending', max_length=16)),
                ('scopes_granted', models.CharField(blank=True, default='', max_length=512)),
                ('access_token_encrypted', models.TextField(blank=True, default='')),
                ('refresh_token_encrypted', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'provider', 'external_account_id')},
            },
        ),
    ]
