# Generated by Django 6.0.3 on 2026-04-03 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_release_distributionjob_distributionevent_track_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='auto_apply_collab_royalties',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='release',
            name='collab_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_releases', to='backend.collabroyaltyagreement'),
        ),
        migrations.AddField(
            model_name='release',
            name='premium_required',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ReleaseContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('writer', 'Writer'), ('performer', 'Performer'), ('mix_engineer', 'Mix Engineer'), ('producer', 'Producer'), ('visual_designer', 'Visual Designer (Cover)'), ('business_manager', 'Business Manager'), ('other', 'Other')], max_length=32)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Royalty percentage for this role', max_digits=5)),
                ('source', models.CharField(choices=[('agreement', 'Agreement'), ('manual', 'Manual')], default='manual', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_split', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_contributor_snapshots', to='backend.collabroyaltysplit')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_contributions', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='backend.release')),
            ],
            options={
                'ordering': ['role', '-percentage', 'participant_id'],
                'indexes': [models.Index(fields=['release', 'role'], name='backend_rel_release_24e744_idx'), models.Index(fields=['participant', 'role'], name='backend_rel_partici_289f60_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReleaseRoyaltySplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source', models.CharField(choices=[('agreement', 'Agreement'), ('manual', 'Manual')], default='agreement', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_split', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_snapshots', to='backend.collabroyaltysplit')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_royalty_splits', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalty_splits', to='backend.release')),
            ],
            options={
                'ordering': ['-percentage', 'participant_id'],
                'unique_together': {('release', 'participant')},
            },
        ),
    ]
