# Generated by Django 6.0.3 on 2026-04-03 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_release_auto_apply_collab_royalties_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_streams', models.BigIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue_currency', models.CharField(default='USD', max_length=3)),
                ('revenue_settled_date', models.DateField(blank=True, null=True)),
                ('unique_listeners', models.IntegerField(default=0)),
                ('total_saves', models.IntegerField(default=0)),
                ('total_skips', models.IntegerField(default=0)),
                ('earliest_stream_date', models.DateTimeField(blank=True, null=True)),
                ('latest_stream_date', models.DateTimeField(blank=True, null=True)),
                ('platform_breakdown_json', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='backend.release')),
            ],
            options={
                'verbose_name_plural': 'Release Analytics',
            },
        ),
        migrations.CreateModel(
            name='TrackAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streams', models.BigIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unique_listeners', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('skips', models.IntegerField(default=0)),
                ('skip_rate', models.DecimalField(decimal_places=2, default=0, help_text='Skip rate %', max_digits=5)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, help_text='Completion rate %', max_digits=5)),
                ('average_listen_seconds', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='backend.track')),
            ],
            options={
                'verbose_name_plural': 'Track Analytics',
            },
        ),
        migrations.CreateModel(
            name='ContributorEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=32)),
                ('royalty_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('participant_share', models.DecimalField(decimal_places=2, default=0, help_text='Calculated: total_revenue * royalty_percentage / 100', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('settled_date', models.DateField(blank=True, null=True)),
                ('settled_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payout_method', models.CharField(blank=True, default='', max_length=32)),
                ('payout_status', models.CharField(choices=[('pending', 'Pending Settlement'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='backend.releasecontributor')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_earnings', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_earnings', to='backend.release')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('contributor', 'release')},
            },
        ),
        migrations.CreateModel(
            name='StreamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('event_type', models.CharField(choices=[('stream', 'Stream'), ('preview', 'Preview'), ('sale', 'Sale'), ('skip', 'Skip'), ('save', 'Save'), ('share', 'Share')], max_length=16)),
                ('event_date', models.DateField()),
                ('count', models.IntegerField(default=1)),
                ('revenue', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('listener_country', models.CharField(blank=True, default='', max_length=2)),
                ('listener_device_type', models.CharField(blank=True, default='', max_length=32)),
                ('raw_payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_events', to='backend.track')),
            ],
            options={
                'ordering': ['-event_date', '-id'],
                'indexes': [models.Index(fields=['track', 'event_date'], name='backend_str_track_i_e2d6c8_idx'), models.Index(fields=['provider', 'event_type', 'event_date'], name='backend_str_provide_5b80bb_idx')],
            },
        ),
    ]
