# Generated by Django 6.0.3 on 2026-04-03 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_releaseanalytics_trackanalytics_contributorearnings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumFeature',
            fields=[
                ('feature_key', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('feature_type', models.CharField(choices=[('distribution', 'Music Distribution'), ('unlimited_contributors', 'Unlimited Contributors'), ('advanced_analytics', 'Advanced Analytics'), ('pending_edits', 'Pending Release Edits'), ('lyrics_management', 'Lyrics Management'), ('priority_support', 'Priority Support'), ('api_access', 'API Access'), ('white_label', 'White Label Branding'), ('pro_settle_fast', 'Fast Settlement (48h)'), ('master_analytics', 'Master/Catalog Analytics')], max_length=32)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('yearly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['monthly_price', 'feature_key'],
            },
        ),
        migrations.CreateModel(
            name='PremiumBundle',
            fields=[
                ('bundle_key', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('bundle_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('yearly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('features', models.ManyToManyField(related_name='bundles', to='backend.premiumfeature')),
            ],
            options={
                'ordering': ['display_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='UserPremiumFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('paused', 'Paused')], default='active', max_length=16)),
                ('subscription_start', models.DateTimeField(auto_now_add=True)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=16)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('auto_renew', models.BooleanField(default=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='backend.premiumfeature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_features', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-subscription_start'],
                'unique_together': {('user', 'feature')},
            },
        ),
    ]
