# Generated by Django 6.0.5 on 2026-05-30 15:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=120)),
                ('name', models.CharField(blank=True, default='', max_length=160)),
                ('genre', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(blank=True, default='', max_length=120)),
                ('stage', models.CharField(choices=[('watching', 'Watching'), ('contacted', 'Contacted'), ('shortlisted', 'Shortlisted'), ('signed', 'Signed'), ('passed', 'Passed')], default='watching', max_length=12)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoutz_prospectz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoutingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=240)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoutz_reportz', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportz', to='scoutz.prospect')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoutz_taskz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['done', '-created_at'],
            },
        ),
    ]
