# Generated by Django 6.0.6 on 2026-06-05 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutOpening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label_or_company', models.CharField(blank=True, default='', max_length=160)),
                ('title', models.CharField(max_length=200)),
                ('looking_for', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('open', models.BooleanField(default=True)),
                ('owner_adult_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoutz_openingz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TalentListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=160)),
                ('genre', models.CharField(blank=True, default='', max_length=64)),
                ('pitch', models.TextField(blank=True, default='')),
                ('looking_for', models.CharField(choices=[('deal', 'Record Deal'), ('distribution', 'Distribution'), ('management', 'Management'), ('sync', 'Sync / Licensing'), ('feature', 'Features / Collabs')], default='deal', max_length=16)),
                ('links', models.JSONField(blank=True, default=list)),
                ('post_ref', models.CharField(blank=True, default='', max_length=64)),
                ('open', models.BooleanField(default=True)),
                ('owner_adult_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoutz_talent_listingz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoutInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('passed', 'Passed')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoutz_interestz', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interestz', to='scoutz.talentlisting')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'listing')},
            },
        ),
    ]
