# Generated by Django 5.2.16 on 2026-07-31 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("economy", "0048_profile_genres"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollabProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("original", "OriginalZ"),
                            ("cover", "CoverZ 🫴🏼"),
                            ("remix", "RemixeZ 🔄"),
                        ],
                        db_index=True,
                        default="original",
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("brief", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("active", "Active"),
                            ("review", "In review"),
                            ("released", "Released"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=12,
                    ),
                ),
                (
                    "source_credit",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("seeking", models.JSONField(blank=True, default=list)),
                ("genres", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deal",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collab_project",
                        to="economy.collabdeal",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collab_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "result_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collab_results",
                        to="economy.post",
                    ),
                ),
                (
                    "source_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collab_derivatives",
                        to="economy.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CollabMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("collaborator", "Collaborator"),
                            ("invited", "Invited"),
                        ],
                        default="collaborator",
                        max_length=14,
                    ),
                ),
                ("persona", models.CharField(blank=True, default="", max_length=40)),
                (
                    "contribution",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("split_percent", models.PositiveIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collab_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="collabz.collabproject",
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
                "unique_together": {("project", "user")},
            },
        ),
    ]
