# Generated by Django 5.2.16 on 2026-07-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collabz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collabproject",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
