# Generated by Django 5.2.16 on 2026-07-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collabz", "0002_collabproject_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="collabproject",
            name="requirements",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
