# Generated by Django 6.0.5 on 2026-05-29 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFlags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_status', models.CharField(choices=[('unknown', 'Unknown / unverified'), ('youth', 'Youth (under 18, parental consent)'), ('adult', 'Adult (18+, verified)')], default='unknown', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcz_flags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
