# Generated by Django 6.0.5 on 2026-05-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflags',
            name='adult_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userflags',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userflags',
            name='parental_consent',
            field=models.BooleanField(default=False),
        ),
    ]
