# Generated by Django 6.0.5 on 2026-06-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_userflags_adult_verified_userflags_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflags',
            name='stripe_session_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
