# Generated by Django 5.2.15 on 2026-07-02 16:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(blank=True, default='', max_length=60)),
                ('skill', models.CharField(db_index=True, max_length=60)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, default='')),
                ('media_ref', models.CharField(blank=True, default='', help_text='Reference id from the platform upload pipeline.', max_length=255)),
                ('preview_ref', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('premium', 'Premium tier'), ('statz', 'StatZ tier'), ('private', 'Only me')], default='public', max_length=10)),
                ('rating_snapshot', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LessonPostPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('settled', models.BooleanField(default=False)),
                ('external_ref', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='lessonz.lessonpost')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_post_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'student')},
            },
        ),
    ]
