# Generated by Django 5.2.15 on 2026-07-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonz', '0002_lessonpost_lessonpostpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonbooking',
            name='method',
            field=models.CharField(choices=[('in_person', 'In person'), ('remote', 'Remote'), ('callz', 'CallZ video (StatZ)')], default='in_person', max_length=12),
        ),
        migrations.AddField(
            model_name='lessonoffer',
            name='callz_ok',
            field=models.BooleanField(default=False, help_text='Deliver over CallZ video. StatZ-exclusive on both sides.'),
        ),
    ]
