# Generated by Django 5.2.17 on 2026-10-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessonz", "0003_lessonbooking_method_lessonoffer_callz_ok"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonoffer",
            name="gates",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
