# Generated by Django 5.2.16 on 2026-07-31 00:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("economy", "0048_profile_genres"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("freestyle", "Freestyle 🆓"),
                            ("1v1", "1v1 1️⃣"),
                            ("cypher", "Battle Cypher 🧑\u200d🤝\u200d🧑"),
                        ],
                        db_index=True,
                        default="1v1",
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("rules", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("live", "Live"),
                            ("voting", "Voting"),
                            ("settled", "Settled"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=12,
                    ),
                ),
                ("opens_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "closes_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "winner",
                    models.CharField(
                        blank=True,
                        choices=[("a", "Side A"), ("b", "Side B")],
                        default="",
                        max_length=1,
                    ),
                ),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("settlement", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battles_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battles_as_a",
                        to="economy.post",
                    ),
                ),
                (
                    "post_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battles_as_b",
                        to="economy.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BattleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("a", "Side A"), ("b", "Side B")], max_length=1
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="battlez.battle",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battle_entries",
                        to="economy.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
                "unique_together": {("battle", "user")},
            },
        ),
        migrations.CreateModel(
            name="BattleVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("a", "Side A"), ("b", "Side B")], max_length=1
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="battlez.battle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("battle", "user")},
            },
        ),
        migrations.CreateModel(
            name="Bet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("a", "Side A"), ("b", "Side B")], max_length=1
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("money", "Money"), ("spinaz", "SpinAZ")], max_length=8
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("payout", models.PositiveIntegerField(default=0)),
                ("settled", models.BooleanField(default=False)),
                ("refunded", models.BooleanField(default=False)),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to="battlez.battle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_bets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["placed_at"],
                "indexes": [
                    models.Index(
                        fields=["battle", "currency", "side"],
                        name="battlez_bet_battle__55b3e3_idx",
                    )
                ],
            },
        ),
    ]
