"""What each library exercise IS, for the Coach's superset pairing: compound or isolation, push or pull.

A DECLARED table keyed by exercise name, not an inference at request time. Names, not
ids: library ids are not the same in every database (members' custom exercises take
ids between migrations), a name is. Custom exercises are never in here and are never
paired.

`mechanic` is "compound" (two or more prime-mover muscle groups across two or more
joints), "isolation" (one joint, one muscle) or "other" (cardio, holds, carries —
never paired by a mechanic rule). `force` is "push", "pull" or "neither" (core, cardio,
holds). They were assigned by three independent classifiers working from different
angles (biomechanics, kinesiology, bodybuilding programming); the six lifts they did not
agree on were settled by a fourth with the single-joint and push/pull facts stated.
`test_superset` fails when a library exercise has no row, so adding a lift to the library
without classifying it is a red test and not a Coach that silently skips it.
"""
TABLE = {
    "Bench Press": ("compound", "push"),
    "Push-Up": ("compound", "push"),
    "Dumbbell Fly": ("isolation", "push"),
    "Pull-Up": ("compound", "pull"),
    "Barbell Row": ("compound", "pull"),
    "Lat Pulldown": ("compound", "pull"),
    "Deadlift": ("compound", "pull"),
    "Overhead Press": ("compound", "push"),
    "Lateral Raise": ("isolation", "push"),
    "Face Pull": ("compound", "pull"),
    "Bicep Curl": ("isolation", "pull"),
    "Tricep Pushdown": ("isolation", "push"),
    "Dip": ("compound", "push"),
    "Squat": ("compound", "push"),
    "Leg Press": ("compound", "push"),
    "Lunge": ("compound", "push"),
    "Dumbbell Romanian Deadlift": ("compound", "pull"),
    "Calf Raise": ("isolation", "push"),
    "Plank": ("other", "neither"),
    "Hanging Leg Raise": ("isolation", "neither"),
    "Cable Crunch": ("isolation", "neither"),
    "Russian Twist": ("isolation", "neither"),
    "Running": ("other", "neither"),
    "Rowing Machine": ("other", "neither"),
    "Burpee": ("compound", "push"),
    "Kettlebell Swing": ("compound", "pull"),
    "Clean and Press": ("compound", "push"),
    "EZ Bar Curl": ("isolation", "pull"),
    "EZ Bar Skullcrusher": ("isolation", "push"),
    "EZ Bar Upright Row": ("compound", "pull"),
    "Kettlebell Goblet Squat": ("compound", "push"),
    "Kettlebell Clean and Press": ("compound", "push"),
    "Kettlebell Row": ("compound", "pull"),
    "Turkish Get-Up": ("other", "neither"),
    "Cable Row": ("compound", "pull"),
    "Lat Pulldown (Cable)": ("compound", "pull"),
    "Cable Fly": ("isolation", "push"),
    "Cable Face Pull": ("compound", "pull"),
    "Cable Woodchopper": ("compound", "neither"),
    "Incline Barbell Bench Press": ("compound", "push"),
    "Decline Barbell Bench Press": ("compound", "push"),
    "Incline Dumbbell Press": ("compound", "push"),
    "Decline Dumbbell Press": ("compound", "push"),
    "Tricep Kickback": ("isolation", "push"),
    "Dumbbell Tricep Extension": ("isolation", "push"),
    "Barbell Tricep Extension": ("isolation", "push"),
    "Barbell Curl": ("isolation", "pull"),
    "Dumbbell Front Raise": ("isolation", "push"),
    "Dumbbell Shoulder Press": ("compound", "push"),
    "Dumbbell Row": ("compound", "pull"),
    "Zottman Curl": ("isolation", "pull"),
    "Dumbbell Bench Press": ("compound", "push"),
    "Reverse Barbell Curl": ("isolation", "pull"),
    "Dumbbell Squat": ("compound", "push"),
    "Dumbbell Deadlift": ("compound", "pull"),
    "Machine Bench Press": ("compound", "push"),
    "Seated Leg Extension": ("isolation", "push"),
    "Seated Leg Curl": ("isolation", "pull"),
    "Lying Leg Curl": ("isolation", "pull"),
    "Seated Calf Raise": ("isolation", "push"),
    "Glute Bridge": ("compound", "push"),
    "Seated Hip Abduction": ("isolation", "neither"),
    "Crunch": ("isolation", "neither"),
    "Seated Ab Crunch": ("isolation", "neither"),
    "Pec Deck": ("isolation", "push"),
    "Seated Band Chest Press": ("compound", "push"),
    "Seated Machine Shoulder Press": ("compound", "push"),
    "Chest-Supported Dumbbell Row": ("compound", "pull"),
    "Seated Band Row": ("compound", "pull"),
    "Seated Hammer Curl": ("isolation", "pull"),
    "Seated Arm Crank": ("other", "neither"),
    "Hack Squat": ("compound", "push"),
    "Single-Leg Press": ("compound", "push"),
    "Seated Hip Adduction": ("isolation", "neither"),
    "Bodyweight Box Squat": ("compound", "push"),
    "Wall Sit": ("other", "neither"),
    "Bodyweight Step-Up": ("compound", "push"),
    "Bodyweight Reverse Lunge": ("compound", "push"),
    "Single-Leg Glute Bridge": ("compound", "push"),
    "Clamshell": ("isolation", "neither"),
    "Side-Lying Leg Raise": ("isolation", "neither"),
    "Seated Tibialis Raise": ("isolation", "pull"),
    "Reverse Crunch": ("isolation", "neither"),
    "Lying Leg Raise": ("isolation", "neither"),
    "Bicycle Crunch": ("isolation", "neither"),
    "Seated Trunk Rotation": ("isolation", "neither"),
    "Lying Pelvic Tilt": ("isolation", "neither"),
    "Abdominal Brace Hold": ("other", "neither"),
    "Recumbent Bike": ("other", "neither"),
    "Walking": ("other", "neither"),
    "Barbell Upright Row": ("compound", "pull"),
    "Dumbbell Upright Row": ("compound", "pull"),
    "Cable Upright Row": ("compound", "pull"),
    "Arnold Press": ("compound", "push"),
    "Barbell Shrug": ("isolation", "pull"),
    "Dumbbell Shrug": ("isolation", "pull"),
    "Dumbbell Rear Delt Fly": ("isolation", "pull"),
    "Reverse Pec Deck": ("isolation", "pull"),
    "Cable Lateral Raise": ("isolation", "push"),
    "Barbell Front Raise": ("isolation", "push"),
    "Landmine Press": ("compound", "push"),
    "Band Pull-Apart": ("isolation", "pull"),
    "Band Lateral Raise": ("isolation", "push"),
    "Pike Push-Up": ("compound", "push"),
    "Incline Dumbbell Fly": ("isolation", "push"),
    "Cable Crossover": ("isolation", "push"),
    "Low-to-High Cable Fly": ("isolation", "push"),
    "Dumbbell Pullover": ("isolation", "pull"),
    "Smith Machine Bench Press": ("compound", "push"),
    "Incline Push-Up": ("compound", "push"),
    "Decline Push-Up": ("compound", "push"),
    "Chin-Up": ("compound", "pull"),
    "T-Bar Row": ("compound", "pull"),
    "Pendlay Row": ("compound", "pull"),
    "Seated Machine Row": ("compound", "pull"),
    "Straight-Arm Pulldown": ("isolation", "pull"),
    "Inverted Row": ("compound", "pull"),
    "Back Extension": ("isolation", "pull"),
    "Good Morning": ("compound", "pull"),
    "Rack Pull": ("compound", "pull"),
    "Superman": ("isolation", "pull"),
    "Hammer Curl": ("isolation", "pull"),
    "Preacher Curl": ("isolation", "pull"),
    "Dumbbell Preacher Curl": ("isolation", "pull"),
    "Concentration Curl": ("isolation", "pull"),
    "Incline Dumbbell Curl": ("isolation", "pull"),
    "Cable Curl": ("isolation", "pull"),
    "Band Curl": ("isolation", "pull"),
    "Machine Bicep Curl": ("isolation", "pull"),
    "Close-Grip Bench Press": ("compound", "push"),
    "Overhead Cable Tricep Extension": ("isolation", "push"),
    "Rope Pushdown": ("isolation", "push"),
    "Dumbbell Skullcrusher": ("isolation", "push"),
    "Bench Dip": ("compound", "push"),
    "Diamond Push-Up": ("compound", "push"),
    "Machine Tricep Extension": ("isolation", "push"),
    "Band Tricep Pushdown": ("isolation", "push"),
    "Wrist Curl": ("isolation", "pull"),
    "Reverse Wrist Curl": ("isolation", "pull"),
    "Barbell Wrist Curl": ("isolation", "pull"),
    "Farmer's Walk": ("other", "neither"),
    "Dead Hang": ("other", "neither"),
    "Ab Wheel Rollout": ("compound", "neither"),
    "Side Plank": ("other", "neither"),
    "Mountain Climber": ("other", "neither"),
    "Sit-Up": ("isolation", "neither"),
    "Oblique Crunch": ("isolation", "neither"),
    "Dead Bug": ("other", "neither"),
    "Bird Dog": ("other", "neither"),
    "Hollow Body Hold": ("other", "neither"),
    "V-Up": ("isolation", "neither"),
    "Flutter Kick": ("isolation", "neither"),
    "Pallof Press": ("other", "neither"),
    "Captain's Chair Leg Raise": ("isolation", "neither"),
    "Front Squat": ("compound", "push"),
    "Goblet Squat": ("compound", "push"),
    "Bulgarian Split Squat": ("compound", "push"),
    "Stiff-Leg Deadlift": ("compound", "pull"),
    "Sumo Deadlift": ("compound", "pull"),
    "Walking Lunge": ("compound", "push"),
    "Dumbbell Step-Up": ("compound", "push"),
    "Smith Machine Squat": ("compound", "push"),
    "Nordic Hamstring Curl": ("isolation", "pull"),
    "Pistol Squat": ("compound", "push"),
    "Jump Squat": ("compound", "push"),
    "Bodyweight Squat": ("compound", "push"),
    "Barbell Hip Thrust": ("compound", "push"),
    "Dumbbell Hip Thrust": ("compound", "push"),
    "Cable Pull-Through": ("compound", "pull"),
    "Cable Glute Kickback": ("isolation", "push"),
    "Donkey Kick": ("isolation", "push"),
    "Fire Hydrant": ("isolation", "neither"),
    "Banded Lateral Walk": ("isolation", "neither"),
    "Sumo Squat": ("compound", "push"),
    "Bodyweight Calf Raise": ("isolation", "push"),
    "Dumbbell Calf Raise": ("isolation", "push"),
    "Leg Press Calf Raise": ("isolation", "push"),
    "Stationary Bike": ("other", "neither"),
    "Elliptical": ("other", "neither"),
    "Stair Climber": ("other", "neither"),
    "Jump Rope": ("other", "neither"),
    "Jumping Jack": ("other", "neither"),
    "Barbell Thruster": ("compound", "push"),
    "Dumbbell Thruster": ("compound", "push"),
    "Power Clean": ("compound", "pull"),
    "Kettlebell Snatch": ("compound", "pull"),
}
