# Generated by Django 6.0.6 on 2026-06-06 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('genre', models.CharField(blank=True, default='', max_length=48)),
                ('subgenre', models.CharField(blank=True, default='', max_length=48)),
                ('engine', models.CharField(choices=[('web', 'Web (HTML/JS/Canvas)'), ('unreal', 'Unreal Engine')], default='web', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('building', 'Building'), ('playable', 'Playable'), ('published', 'Published')], default='draft', max_length=10)),
                ('occ_project_ref', models.CharField(blank=True, default='', max_length=120)),
                ('auto_mode', models.BooleanField(default=False)),
                ('tier_at_creation', models.CharField(default='premium', max_length=12)),
                ('exported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamez', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OCCMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('code', 'Code'), ('build', 'Game Build'), ('other', 'Other')], default='image', max_length=8)),
                ('url', models.URLField(blank=True, default='')),
                ('source', models.CharField(default='occ', max_length=16)),
                ('routed_to', models.CharField(choices=[('intelligence', 'Routed to Intelligence'), ('export', 'Exported by owner')], default='intelligence', max_length=16)),
                ('intelligence_ref', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediaz', to='gamez.game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occ_mediaz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
