# Generated by Django 5.2.16 on 2026-07-30 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=60)),
                ("name", models.CharField(max_length=120)),
                ("muscle", models.CharField(db_index=True, max_length=20)),
                ("secondary", models.JSONField(blank=True, default=list)),
                ("equipment", models.JSONField(blank=True, default=list)),
                ("pattern", models.CharField(default="isolation", max_length=16)),
                ("difficulty", models.CharField(default="beginner", max_length=16)),
                ("instructions", models.TextField(blank=True, default="")),
                ("media_url", models.CharField(blank=True, default="", max_length=300)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bodiez_exercises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["muscle", "name"],
            },
        ),
        migrations.CreateModel(
            name="FitnessGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_type", models.CharField(default="habit", max_length=16)),
                ("title", models.CharField(max_length=140)),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=16)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goals",
                        to="bodiez.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bodiez_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GymLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("address", models.CharField(blank=True, default="", max_length=250)),
                ("equipment", models.JSONField(blank=True, default=list)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bodiez_locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("goal", models.CharField(default="general", max_length=20)),
                ("split", models.CharField(default="custom", max_length=24)),
                ("difficulty", models.CharField(default="beginner", max_length=16)),
                ("days_per_week", models.PositiveSmallIntegerField(default=3)),
                (
                    "bucket",
                    models.CharField(db_index=True, default="anytime", max_length=12),
                ),
                ("scheduled_for", models.DateField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=False)),
                ("equipment", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bodiez_routines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="BodieZItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bucket",
                    models.CharField(db_index=True, default="inbox", max_length=12),
                ),
                ("kind", models.CharField(default="idea", max_length=12)),
                ("title", models.CharField(max_length=200)),
                ("note", models.CharField(blank=True, default="", max_length=1000)),
                ("due_at", models.DateField(blank=True, null=True)),
                ("done", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bodiez_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="bodiez.routine",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RoutineExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("sets", models.PositiveSmallIntegerField(default=3)),
                ("reps", models.PositiveSmallIntegerField(default=10)),
                ("rest_seconds", models.PositiveSmallIntegerField(default=90)),
                (
                    "target_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("tempo", models.CharField(blank=True, default="", max_length=16)),
                (
                    "superset_group",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
                ("is_warmup", models.BooleanField(default=False)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="in_routines",
                        to="bodiez.exercise",
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="bodiez.routine",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(db_index=True, default="active", max_length=12),
                ),
                (
                    "perceived_effort",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="bodiez.gymlocation",
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="bodiez.routine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bodiez_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_number", models.PositiveSmallIntegerField(default=1)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("reps", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("distance_m", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "rpe",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("rir", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "rest_seconds",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_warmup", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sets",
                        to="bodiez.exercise",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="bodiez.workoutsession",
                    ),
                ),
            ],
            options={
                "ordering": ["exercise_id", "set_number", "id"],
            },
        ),
        migrations.CreateModel(
            name="BodyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "body_fat",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "neck",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "shoulders",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "chest",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "waist",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "hips",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "arms",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "thighs",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "calves",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bodiez_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["muscle", "pattern"], name="bodiez_exer_muscle_f8f197_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exercise",
            unique_together={("key", "owner")},
        ),
        migrations.AlterUniqueTogether(
            name="gymlocation",
            unique_together={("owner", "name")},
        ),
        migrations.AddIndex(
            model_name="routine",
            index=models.Index(
                fields=["owner", "bucket"], name="bodiez_rout_owner_i_557126_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routine",
            index=models.Index(
                fields=["is_public", "-updated_at"],
                name="bodiez_rout_is_publ_f12aff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bodiezitem",
            index=models.Index(
                fields=["user", "bucket"], name="bodiez_bodi_user_id_2502a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutsession",
            index=models.Index(
                fields=["user", "-started_at"], name="bodiez_work_user_id_8ee058_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutset",
            index=models.Index(
                fields=["session", "exercise"], name="bodiez_work_session_baba6d_idx"
            ),
        ),
    ]
