# Generated by Django 5.2.16 on 2026-07-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bodiez", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="requires",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
