#!/usr/bin/env python3
"""Generate the text-less Music ConnectZ mark in every format we ship.

One geometry definition, many outputs — so the SVG master, the Android adaptive
icon and the Play Store PNGs can never drift apart. Re-run it after changing a
colour or a bar and everything downstream updates:

    python tools/make_brand_assets.py

The mark is deliberately WORDLESS: five pills whose right edges taper into a
play triangle. It reads as "equalizer" and "press play" at the same time, and it
survives being 48dp on a phone launcher, which a wordmark does not.

Outputs
  brand/logo-mark.svg                          master vector (any size)
  brand/play/icon-512.png                      Play listing icon (required)
  brand/play/feature-graphic-1024x500.png      Play listing graphic (required)
  brand/play/icon-1024.png                     spare for other stores/socials
  android/.../drawable/ic_launcher_background.xml
  android/.../drawable/ic_launcher_foreground.xml
  android/.../drawable/ic_launcher_monochrome.xml
  android/.../mipmap-anydpi-v26/ic_launcher.xml + ic_launcher_round.xml
"""
import os

# ---------------------------------------------------------------- palette
INK = "#140A2E"          # darkest stop
VIOLET = "#3A1078"       # mid stop
ACCENT = "#7C4DFF"       # brand violet — same value the tour's spotlight ring uses
SPARK = "#FF3D9A"        # the tip pill, and the only second colour in the mark
BAR = "#FFFFFF"

# Android adaptive icons are authored on a 108x108 canvas; only the centre 66x66
# is guaranteed visible after the launcher applies its mask and parallax. The
# mark below is 56x56 centred, which keeps it inside that with room to breathe.
CANVAS = 108.0
BAR_W = 8.0
GAP = 4.0
# (height) per pill, left to right — the taper that makes the play triangle.
BAR_HEIGHTS = [56.0, 44.0, 32.0, 20.0, 8.0]

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "android", "app", "src", "main", "res")


def bars(canvas=CANVAS):
    """The mark as (x, y, w, h, is_tip) on a square canvas, centred."""
    total_w = len(BAR_HEIGHTS) * BAR_W + (len(BAR_HEIGHTS) - 1) * GAP
    x0 = (canvas - total_w) / 2.0
    cy = canvas / 2.0
    out = []
    for i, h in enumerate(BAR_HEIGHTS):
        x = x0 + i * (BAR_W + GAP)
        out.append((x, cy - h / 2.0, BAR_W, h, i == len(BAR_HEIGHTS) - 1))
    return out


def pill_path(x, y, w, h):
    """Path data for a fully rounded bar (a circle when h == w)."""
    r = w / 2.0
    if abs(h - w) < 0.01:  # the tip: a dot
        return (
            f"M{x},{y + r}"
            f"a{r},{r} 0 1,0 {w},0"
            f"a{r},{r} 0 1,0 {-w},0Z"
        )
    return (
        f"M{x + r},{y}"
        f"A{r},{r} 0 0 1 {x + w},{y + r}"
        f"L{x + w},{y + h - r}"
        f"A{r},{r} 0 0 1 {x + r},{y + h}"
        f"A{r},{r} 0 0 1 {x},{y + h - r}"
        f"L{x},{y + r}"
        f"A{r},{r} 0 0 1 {x + r},{y}Z"
    )


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("wrote", os.path.relpath(path, ROOT))


# ---------------------------------------------------------------- SVG master
def svg_master():
    paths = "\n".join(
        f'    <path d="{pill_path(x, y, w, h)}" fill="{SPARK if tip else BAR}"/>'
        for x, y, w, h, tip in bars()
    )
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108" width="108" height="108" role="img" aria-label="Music ConnectZ">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="{INK}"/>
      <stop offset="0.55" stop-color="{VIOLET}"/>
      <stop offset="1" stop-color="{ACCENT}"/>
    </linearGradient>
  </defs>
  <rect width="108" height="108" rx="24" fill="url(#bg)"/>
  <g>
{paths}
  </g>
</svg>
"""


# ---------------------------------------------------------------- Android vectors
def vector_background():
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tools/make_brand_assets.py — edit that, not this. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:startX="0" android:startY="0"
                android:endX="108" android:endY="108"
                android:type="linear">
                <item android:color="{INK}" android:offset="0" />
                <item android:color="{VIOLET}" android:offset="0.55" />
                <item android:color="{ACCENT}" android:offset="1" />
            </gradient>
        </aapt:attr>
    </path>
</vector>
"""


def vector_mark(single_colour=None):
    paths = "\n".join(
        f'    <path\n'
        f'        android:pathData="{pill_path(x, y, w, h)}"\n'
        f'        android:fillColor="{single_colour or (SPARK if tip else BAR)}" />'
        for x, y, w, h, tip in bars()
    )
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tools/make_brand_assets.py — edit that, not this. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
{paths}
</vector>
"""


ADAPTIVE = """<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tools/make_brand_assets.py — edit that, not this. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <!-- Android 13+ themed icons: the launcher tints this itself. -->
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
"""


# ---------------------------------------------------------------- PNG (Play Store)
def _hex(c):
    c = c.lstrip("#")
    return tuple(int(c[i:i + 2], 16) for i in (0, 2, 4))


def _lerp(a, b, t):
    return tuple(round(a[i] + (b[i] - a[i]) * t) for i in range(3))


def _gradient(size):
    """Diagonal three-stop gradient matching the SVG, drawn per-pixel row."""
    from PIL import Image

    w, h = size
    img = Image.new("RGB", size)
    ink, violet, accent = _hex(INK), _hex(VIOLET), _hex(ACCENT)
    px = img.load()
    for y in range(h):
        for x in range(w):
            t = ((x / max(w - 1, 1)) + (y / max(h - 1, 1))) / 2.0
            if t <= 0.55:
                px[x, y] = _lerp(ink, violet, t / 0.55)
            else:
                px[x, y] = _lerp(violet, accent, (t - 0.55) / 0.45)
    return img


def _draw_mark(img, box, scale=1.0):
    """Draw the wordless mark centred in ``box`` = (cx, cy, side)."""
    from PIL import ImageDraw

    cx, cy, side = box
    unit = (side / CANVAS) * scale
    draw = ImageDraw.Draw(img)
    for x, y, w, h, tip in bars():
        # bars() is centred on the 108 canvas; re-centre onto (cx, cy)
        x0 = cx + (x - CANVAS / 2) * unit
        y0 = cy + (y - CANVAS / 2) * unit
        draw.rounded_rectangle(
            [x0, y0, x0 + w * unit, y0 + h * unit],
            radius=(w * unit) / 2,
            fill=_hex(SPARK if tip else BAR),
        )


def png_icon(path, side, corner_ratio=0.22, ss=4):
    """Square store icon. Supersampled, then downscaled for clean edges."""
    from PIL import Image, ImageDraw

    big = side * ss
    img = _gradient((big, big)).convert("RGBA")
    _draw_mark(img, (big / 2, big / 2, big * 0.62))
    if corner_ratio:
        # Play wants a full-bleed square for the 512 listing icon and applies
        # its own rounding, but a soft radius here still looks right anywhere
        # else the file gets used.
        mask = Image.new("L", (big, big), 0)
        ImageDraw.Draw(mask).rounded_rectangle(
            [0, 0, big - 1, big - 1], radius=int(big * corner_ratio), fill=255
        )
        img.putalpha(mask)
    img = img.resize((side, side), Image.LANCZOS)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    img.save(path, "PNG")
    print("wrote", os.path.relpath(path, ROOT), f"{side}x{side}")


def png_feature_graphic(path, w=1024, h=500, ss=2):
    """Play's feature graphic. No text — the mark is the whole composition."""
    from PIL import Image

    img = _gradient((w * ss, h * ss)).convert("RGBA")
    # Centred on purpose: Play crops this graphic differently across surfaces,
    # and anything parked near an edge is what gets cut.
    _draw_mark(img, (w * ss * 0.5, h * ss * 0.5, h * ss * 0.62))
    img = img.resize((w, h), Image.LANCZOS).convert("RGB")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    img.save(path, "PNG")
    print("wrote", os.path.relpath(path, ROOT), f"{w}x{h}")


def main():
    write(os.path.join(ROOT, "brand", "logo-mark.svg"), svg_master())

    write(os.path.join(RES, "drawable", "ic_launcher_background.xml"), vector_background())
    write(os.path.join(RES, "drawable", "ic_launcher_foreground.xml"), vector_mark())
    write(os.path.join(RES, "drawable", "ic_launcher_monochrome.xml"), vector_mark(BAR))
    write(os.path.join(RES, "mipmap-anydpi-v26", "ic_launcher.xml"), ADAPTIVE)
    write(os.path.join(RES, "mipmap-anydpi-v26", "ic_launcher_round.xml"), ADAPTIVE)

    play = os.path.join(ROOT, "brand", "play")
    png_icon(os.path.join(play, "icon-512.png"), 512)
    png_icon(os.path.join(play, "icon-1024.png"), 1024)
    png_feature_graphic(os.path.join(play, "feature-graphic-1024x500.png"))


if __name__ == "__main__":
    main()
