# Generated by Django 5.2.15 on 2026-06-30 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MimeZSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lipsync', 'Lipsync'), ('selfie', 'Selfie expression'), ('dance', 'Dance')], default='lipsync', max_length=12)),
                ('drill_key', models.CharField(blank=True, default='', max_length=80)),
                ('caption', models.CharField(blank=True, default='', max_length=240)),
                ('media_ref', models.CharField(blank=True, default='', help_text='Reference id from the platform upload pipeline (no raw media here).', max_length=255)),
                ('score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mimez_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
