# Generated by Django 6.0.6 on 2026-06-05 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managez', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementSeeking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=160)),
                ('genre', models.CharField(blank=True, default='', max_length=64)),
                ('pitch', models.TextField(blank=True, default='')),
                ('needs', models.CharField(blank=True, default='', max_length=200)),
                ('links', models.JSONField(blank=True, default=list)),
                ('post_ref', models.CharField(blank=True, default='', max_length=64)),
                ('open', models.BooleanField(default=True)),
                ('owner_adult_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managez_seekingz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerOpening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, default='', max_length=160)),
                ('title', models.CharField(max_length=200)),
                ('specialties', models.CharField(blank=True, default='', max_length=200)),
                ('roster_size', models.PositiveIntegerField(default=0)),
                ('body', models.TextField(blank=True, default='')),
                ('open', models.BooleanField(default=True)),
                ('owner_adult_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managez_openingz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagementOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('talking', 'In Talks'), ('signed', 'Signed'), ('passed', 'Passed')], default='new', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managez_offerz', to=settings.AUTH_USER_MODEL)),
                ('seeking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerz', to='managez.managementseeking')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'seeking')},
            },
        ),
    ]
