# Generated by Django 6.0.6 on 2026-06-05 19:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drill_id', models.UUIDField(db_index=True)),
                ('track_key', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(choices=[('imagez', 'Edited in ImageZ'), ('import', 'Imported file'), ('asset', 'From DesignZ asset')], default='imagez', max_length=8)),
                ('artifact_url', models.URLField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissionz', to='designz.asset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designz_submissionz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
