# Generated by Django 5.2.16 on 2026-07-18 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0006_face_facerating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("bio", models.CharField(blank=True, default="", max_length=500)),
                ("location", models.CharField(blank=True, default="", max_length=120)),
                ("gender", models.CharField(blank=True, default="", max_length=24)),
                ("birthday", models.CharField(blank=True, default="", max_length=10)),
                ("sign", models.CharField(blank=True, default="", max_length=16)),
                ("nationalities", models.JSONField(blank=True, default=list)),
                ("regions", models.JSONField(blank=True, default=list)),
                ("substances", models.JSONField(blank=True, default=dict)),
                ("sober", models.BooleanField(default=False)),
                ("attracted_to", models.JSONField(blank=True, default=list)),
                ("asexual", models.BooleanField(default=False)),
                ("traits", models.JSONField(blank=True, default=list)),
                ("personas", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcz_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
