# Generated by Django 5.2.16 on 2026-07-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0008_merchitem_merchpurchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("premium", "Premium"),
                    ("statz", "StatZ"),
                    ("debug", "Debug"),
                ],
                default="free",
                max_length=16,
            ),
        ),
    ]
