# Generated by Django 5.2.16 on 2026-07-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0010_profile_links_socialcomment_reaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="last_seen",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
