# Generated by Django 5.2.16 on 2026-07-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0011_membership_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="lifetime",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
