# Generated by Django 5.2.16 on 2026-07-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0012_membership_lifetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
