# Generated by Django 5.2.16 on 2026-07-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0013_membership_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="founding",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
