# Generated by Django 5.2.16 on 2026-07-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0015_profile_avatar_overallrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="share_location",
            field=models.BooleanField(default=False),
        ),
    ]
