# Generated by Django 5.2.16 on 2026-07-19 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0016_profile_lat_profile_lng_profile_share_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectZWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fmt",
                    models.CharField(
                        choices=[
                            ("reelz", "ReelZ"),
                            ("episodez", "EpisodeZ"),
                            ("moviez", "MovieZ"),
                        ],
                        default="reelz",
                        max_length=12,
                    ),
                ),
                ("video_type", models.CharField(blank=True, default="", max_length=40)),
                ("mood", models.CharField(blank=True, default="", max_length=32)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("duration_sec", models.PositiveIntegerField(default=0)),
                ("contributors", models.JSONField(blank=True, default=list)),
                ("ai_rating", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directz_works",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DirectZRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveSmallIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directz_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="economy.directzwork",
                    ),
                ),
            ],
            options={
                "unique_together": {("rater", "work")},
            },
        ),
    ]
