# Generated by Django 5.2.16 on 2026-07-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0017_directzwork_directzrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="last_paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="last_payment_kind",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="membership",
            name="last_payment_ref",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
