# Generated by Django 5.2.16 on 2026-07-20 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0024_alter_notification_kind_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollabDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=160)),
                (
                    "currency",
                    models.CharField(
                        choices=[("money", "Money"), ("spinaz", "SpinAZ")],
                        default="money",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("funded", "Funded"),
                            ("delivered", "Delivered"),
                            ("released", "Released"),
                            ("disputed", "Disputed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("stake_spinaz", models.PositiveIntegerField(default=0)),
                ("participants", models.JSONField(blank=True, default=list)),
                ("held_cents", models.PositiveIntegerField(default=0)),
                ("held_spinaz", models.PositiveIntegerField(default=0)),
                ("held_stake_spinaz", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "auto_release_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collab_deals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
