# Generated by Django 5.2.16 on 2026-07-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0027_autotopup"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="verified_18plus",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="verified_18plus_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
