# Generated by Django 5.2.16 on 2026-07-20 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "economy",
            "0029_message_media_type_message_media_url_post_media_url_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=600)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("safe", models.BooleanField(default=True)),
                ("scanned", models.BooleanField(default=False)),
                ("threat", models.CharField(blank=True, default="", max_length=60)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_counters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("owner", "url")},
            },
        ),
        migrations.CreateModel(
            name="LinkClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("active_seconds", models.PositiveIntegerField(default=0)),
                ("rewarded", models.BooleanField(default=False)),
                ("day", models.DateField()),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clicker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_clicks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "counter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_events",
                        to="economy.linkcounter",
                    ),
                ),
            ],
            options={
                "unique_together": {("counter", "clicker", "day")},
            },
        ),
    ]
