# Generated by Django 5.2.16 on 2026-07-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0030_linkcounter_linkclick"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_album",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="items",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
