# Generated by Django 5.2.16 on 2026-07-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0032_face_tagged"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemrating",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="itemrating",
            name="edit_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="itemrating",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="edit_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="message",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="edit_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="post",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialcomment",
            name="edit_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="socialcomment",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
