# Generated by Django 5.2.16 on 2026-07-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0033_itemrating_created_at_itemrating_edit_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="directzwork",
            name="media_type",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="directzwork",
            name="media_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
