# Generated by Django 5.2.16 on 2026-07-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0034_directzwork_media_type_directzwork_media_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="directzwork",
            name="genre",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
