# Generated by Django 5.2.16 on 2026-07-21 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0035_directzwork_genre"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commercial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("sponsor", models.CharField(blank=True, default="", max_length=120)),
                ("media_url", models.CharField(blank=True, default="", max_length=500)),
                (
                    "media_type",
                    models.CharField(blank=True, default="video", max_length=24),
                ),
                ("link_url", models.CharField(blank=True, default="", max_length=600)),
                ("payout_cents", models.PositiveIntegerField(default=1)),
                ("min_watch_seconds", models.PositiveIntegerField(default=15)),
                ("daily_cap_per_user", models.PositiveIntegerField(default=3)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commercials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AdView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("watched_seconds", models.PositiveIntegerField(default=0)),
                ("rewarded", models.BooleanField(default=False)),
                ("reward_spinaz", models.PositiveIntegerField(default=0)),
                ("day", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "commercial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="economy.commercial",
                    ),
                ),
            ],
        ),
    ]
