# Generated by Django 5.2.16 on 2026-07-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0036_commercial_adview"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="promptz",
            field=models.IntegerField(default=0),
        ),
    ]
