# Generated by Django 5.2.16 on 2026-07-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0038_profile_onboarded_profile_onboarded_at_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="prompt_day",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="wallet",
            name="prompts_used_today",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
