# Generated by Django 5.2.16 on 2026-08-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0040_rewardgrant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="socialcomment",
            name="body",
            field=models.TextField(),
        ),
    ]
