# Generated by Django 5.2.16 on 2026-07-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0041_printproduct_merchdesign_printlisting_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="printorder",
            name="upcharge_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="printproduct",
            name="color_upcharges",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="printproduct",
            name="size_upcharges",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="printproduct",
            name="unavailable",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
