# Generated by Django 5.2.16 on 2026-08-04 19:13

from django.db import migrations, models


def backfill_money(apps, schema_editor):
    """Every row that existed before this was money, in cents. Without it they
    all read as 0 in LogZ — a ledger that starts by understating history is
    worse than no ledger."""
    Transaction = apps.get_model("economy", "Transaction")
    Transaction.objects.update(resource="money")
    for t in Transaction.objects.all().iterator():
        if t.amount != t.amount_cents:
            t.amount = t.amount_cents
            t.save(update_fields=["amount"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0041_alter_profile_bio_alter_socialcomment_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transaction",
            name="resource",
            field=models.CharField(
                choices=[
                    ("money", "Money"),
                    ("spinaz", "SpinaZ"),
                    ("energy", "Energy"),
                    ("promptz", "PromptZ"),
                    ("xp", "XP"),
                ],
                default="money",
                max_length=12,
            ),
        ),
            migrations.RunPython(backfill_money, noop),
    ]
