# Generated by Django 5.2.16 on 2026-08-05 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0041_alter_profile_bio_alter_socialcomment_body"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("habit", "HabitZ"),
                            ("code", "CodeZ"),
                            ("path", "PathZ"),
                            ("mistake", "MistakeZ"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("key", models.CharField(max_length=160)),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                ("app_key", models.CharField(blank=True, default="", max_length=32)),
                ("target", models.CharField(blank=True, default="", max_length=160)),
                ("count", models.PositiveIntegerField(default=0)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("dismissed", models.BooleanField(db_index=True, default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-count", "-last_seen"],
                "unique_together": {("user", "kind", "key")},
            },
        ),
        migrations.CreateModel(
            name="ObservationConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("habit", "HabitZ"),
                            ("code", "CodeZ"),
                            ("path", "PathZ"),
                            ("mistake", "MistakeZ"),
                        ],
                        max_length=12,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observation_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "kind")},
            },
        ),
    ]
