# Generated by Django 5.2.16 on 2026-07-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0042_printorder_upcharge_cents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="printproduct",
            name="print_method",
            field=models.CharField(default="dtg", max_length=16),
        ),
    ]
