# Generated by Django 5.2.16 on 2026-08-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0043_observation_observationconsent"),
    ]

    operations = [
        migrations.AddField(
            model_name="collabdeal",
            name="gates",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="venue",
            name="gates",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
