# Generated by Django 5.2.16 on 2026-07-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0043_printproduct_print_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchdesign",
            name="has_alpha",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="merchdesign",
            name="height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="merchdesign",
            name="width",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
