# Generated by Django 5.2.16 on 2026-07-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0045_projectsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="printorder",
            name="clawback_shortfall_cents",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
