# Generated by Django 5.2.16 on 2026-08-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0045_trial_take"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="energy_accrued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
