# Generated by Django 5.2.16 on 2026-07-30 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0046_printorder_clawback_shortfall_cents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=120)),
                ("purchase_token", models.CharField(max_length=191, unique=True)),
                ("order_id", models.CharField(blank=True, default="", max_length=120)),
                ("kind", models.CharField(default="wallet", max_length=16)),
                ("value_cents", models.PositiveIntegerField(default=0)),
                ("subscription", models.BooleanField(default=False)),
                ("granted", models.BooleanField(default=False)),
                ("acknowledged", models.BooleanField(default=False)),
                ("detail", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="economy_pla_user_id_6fc7cd_idx",
                    )
                ],
            },
        ),
    ]
