# Generated by Django 5.2.16 on 2026-07-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0047_playpurchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="genres",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
