# Generated by Django 5.2.16 on 2026-07-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0048_profile_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="verification_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_detail",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_reason",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_session_id",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unstarted", "Not started"),
                    ("processing", "Checking"),
                    ("verified", "Verified"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                ],
                db_index=True,
                default="unstarted",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
