# Generated by Django 5.2.16 on 2026-08-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0048_playlist_collaborators"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="allow_in_playlists",
            field=models.BooleanField(default=True),
        ),
    ]
