# Generated by Django 5.2.16 on 2026-08-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0049_post_allow_in_playlists"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="genre",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
