# Generated by Django 5.2.16 on 2026-07-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0050_trial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="skill_price_cents",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
