# Generated by Django 5.2.16 on 2026-08-06 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0050_post_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="collabdeal",
            name="source_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collab_deals",
                to="economy.post",
            ),
        ),
    ]
