# Generated by Django 5.2.16 on 2026-08-06 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0051_collabdeal_source_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyboardSkin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallpaper",
                    models.ImageField(blank=True, null=True, upload_to="keyboards/"),
                ),
                ("accent", models.CharField(blank=True, default="", max_length=9)),
                ("key_opacity", models.PositiveSmallIntegerField(default=85)),
                ("dark_keys", models.BooleanField(default=True)),
                (
                    "source_lang",
                    models.CharField(blank=True, default="auto", max_length=12),
                ),
                (
                    "target_lang",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyboard_skin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KeyTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_lang",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                (
                    "target_lang",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                ("chars", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_translations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
