# Generated by Django 5.2.16 on 2026-07-31 16:31

from django.db import migrations, models


def carry_min_attract_over(apps, _schema_editor):
    """Existing venues gate on `min_attract`. Moving to `requirements` without
    bringing it along would silently drop every gate a host already set."""
    Venue = apps.get_model("economy", "Venue")
    for venue in Venue.objects.filter(min_attract__gt=0):
        venue.requirements = {"attractiveness": {"min": float(venue.min_attract),
                                                 "max": None}}
        venue.save(update_fields=["requirements"])


def drop_it(apps, _schema_editor):
    Venue = apps.get_model("economy", "Venue")
    Venue.objects.update(requirements={})


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0051_profile_skill_price_cents"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="requirements",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(carry_min_attract_over, drop_it),
    ]
