# Generated by Django 5.2.16 on 2026-08-06 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0052_keyconnectz"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collabdeal",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="collabdeal",
            name="image_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="collabdeal",
            name="items",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="collabdeal",
            name="lyrics",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="collabdeal",
            name="media_type",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="collabdeal",
            name="media_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="collabdeal",
            name="split_mode",
            field=models.CharField(
                choices=[
                    ("worth", "By agreed worth"),
                    ("rating", "By contribution rating"),
                ],
                default="worth",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="collabdeal",
            name="split_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("media_type", models.CharField(blank=True, default="", max_length=24)),
                ("media_url", models.CharField(blank=True, default="", max_length=500)),
                ("image_url", models.CharField(blank=True, default="", max_length=500)),
                ("lyrics", models.TextField(blank=True, default="")),
                ("genre", models.CharField(blank=True, default="", max_length=40)),
                ("gates", models.JSONField(blank=True, default=dict)),
                ("entry_spinaz", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BattleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=160)),
                ("media_type", models.CharField(blank=True, default="", max_length=24)),
                ("media_url", models.CharField(blank=True, default="", max_length=500)),
                ("image_url", models.CharField(blank=True, default="", max_length=500)),
                ("lyrics", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="economy.battle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "unique_together": {("battle", "user")},
            },
        ),
    ]
