# Generated by Django 5.2.16 on 2026-07-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0052_venue_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="frozen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wallet",
            name="frozen_reason",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="paymentintent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("disputed", "Disputed"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
