# Generated by Django 5.2.16 on 2026-08-06 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0053_collabz_media_battlez"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="held_wager_spinaz",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="battle",
            name="kind",
            field=models.CharField(blank=True, default="1v1", max_length=16),
        ),
        migrations.AddField(
            model_name="battle",
            name="mode",
            field=models.CharField(
                choices=[("1v1", "1v1"), ("open", "Open challenge")],
                default="1v1",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="battles_faced",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="settled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="battles_won",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="battle",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("open", "Open"),
                    ("declined", "Declined"),
                    ("settled", "Settled"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="MoneyBattleVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_battle_vote",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BattleWager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("host", "Host"), ("opponent", "Opponent")],
                        max_length=8,
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=0)),
                ("paid_out", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wagers",
                        to="economy.battle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_wagers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "unique_together": {("battle", "user")},
            },
        ),
    ]
