# Generated by Django 5.2.16 on 2026-08-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0053_wallet_frozen_at_wallet_frozen_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="link_target",
            field=models.CharField(
                choices=[
                    ("tab", "New tab"),
                    ("window", "New window"),
                    ("same", "Same tab"),
                ],
                default="tab",
                max_length=8,
            ),
        ),
    ]
