# Generated by Django 5.2.16 on 2026-08-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0054_battlez_1v1_wagers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battle",
            name="mode",
            field=models.CharField(
                choices=[("1v1", "1v1"), ("open", "Open challenge")],
                default="open",
                max_length=8,
            ),
        ),
    ]
