# Generated by Django 5.2.16 on 2026-08-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0055_battle_mode_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="skills_used",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
