# Generated by Django 5.2.16 on 2026-08-06 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0056_post_skills_used"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OccSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("automation", models.BooleanField(default=False)),
                ("suggestionz", models.BooleanField(default=True)),
                ("pinned_tabs", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occ_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OccTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("edit", "Edit"),
                            ("git", "Git"),
                            ("build", "Build"),
                            ("export", "Export"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Suggested"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("undone", "Undone"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("what", models.TextField(blank=True, default="")),
                ("why", models.TextField(blank=True, default="")),
                ("how", models.TextField(blank=True, default="")),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("eta_seconds", models.PositiveIntegerField(default=0)),
                ("detail", models.TextField(blank=True, default="")),
                ("git_repo", models.CharField(blank=True, default="", max_length=200)),
                (
                    "git_branch",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("git_ref", models.CharField(blank=True, default="", max_length=80)),
                ("undo_payload", models.JSONField(blank=True, default=dict)),
                ("automated", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occ_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
