# Generated by Django 5.2.16 on 2026-08-06 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0057_occ_taskz"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OccOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tab", models.CharField(blank=True, default="", max_length=32)),
                ("input_text", models.TextField(blank=True, default="")),
                ("input_items", models.JSONField(blank=True, default=list)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("media_type", models.CharField(blank=True, default="", max_length=24)),
                ("media_url", models.CharField(blank=True, default="", max_length=500)),
                ("image_url", models.CharField(blank=True, default="", max_length=500)),
                ("lyrics", models.TextField(blank=True, default="")),
                ("items", models.JSONField(blank=True, default=list)),
                ("genre", models.CharField(blank=True, default="", max_length=40)),
                ("skills_used", models.JSONField(blank=True, default=list)),
                ("skill_cost_cents", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shared_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="occ_outputs",
                        to="economy.post",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outputs",
                        to="economy.occtask",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occ_outputs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
