# Generated by Django 5.2.16 on 2026-08-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0058_occ_workz"),
    ]

    operations = [
        migrations.AddField(
            model_name="occtask",
            name="run_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
