# Generated by Django 5.2.16 on 2026-08-07 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0059_occ_run_seconds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=160)),
                (
                    "artist_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("genre", models.CharField(blank=True, default="", max_length=40)),
                ("audio_url", models.CharField(blank=True, default="", max_length=500)),
                ("video_url", models.CharField(blank=True, default="", max_length=500)),
                (
                    "artwork_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("lyrics", models.TextField(blank=True, default="")),
                ("release_date", models.DateField(blank=True, null=True)),
                ("isrc", models.CharField(blank=True, default="", max_length=15)),
                ("explicit", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("submitted", "Submitted"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_post",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="release",
                        to="economy.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
