# Generated by Django 5.2.16 on 2026-08-07 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0061_collab_files_release_deal"),
    ]

    operations = [
        migrations.AddField(
            model_name="collabdeal",
            name="needs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="post",
            name="contributors",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="post",
            name="source_deal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="economy.collabdeal",
            ),
        ),
    ]
