# Generated by Django 5.2.16 on 2026-08-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0066_badgez"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ai_model",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
