# Generated by Django 5.2.16 on 2026-08-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0068_bugz"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="freestyle",
            field=models.BooleanField(default=False),
        ),
    ]
