# Generated by Django 5.2.16 on 2026-08-12 01:18

import apps.economy.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0070_occfile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("genre", models.CharField(blank=True, default="", max_length=40)),
                ("subgenre", models.CharField(blank=True, default="", max_length=80)),
                ("description", models.TextField(blank=True, default="")),
                ("project", models.CharField(default="main", max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("building", "Building"),
                            ("playable", "Playable"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "bundle",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.economy.models.game_bundle_path,
                    ),
                ),
                ("bundle_bytes", models.PositiveBigIntegerField(default=0)),
                ("entry", models.CharField(default="index.html", max_length=200)),
                ("build_detail", models.TextField(blank=True, default="")),
                ("built_at", models.DateTimeField(blank=True, null=True)),
                ("plays", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shared_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games",
                        to="economy.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="GameAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="economy.game",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_assets",
                        to="economy.upload",
                    ),
                ),
            ],
            options={
                "ordering": ("path",),
            },
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["user", "status"], name="economy_gam_user_id_115389_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gameasset",
            constraint=models.UniqueConstraint(
                fields=("game", "path"), name="game_asset_unique_path"
            ),
        ),
    ]
