# Generated by Django 5.2.16 on 2026-08-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0071_game_gameasset_game_economy_gam_user_id_115389_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="build_command",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
