# Generated by Django 5.2.16 on 2026-08-12 16:51

from django.db import migrations, models


def clear_the_old_seeds(apps, schema_editor):
    """Null every rating the retired formula produced.

    `directz_ai_rating` scored contributor count, description length and money
    spent, and called the result a craft estimate. Those numbers are exactly
    what the new rating exists to stop showing, so leaving them on screen while
    replacing the code that makes them would fix the future and keep the past.

    A 0 is the old column default — never rated at all — and would render as
    "0.0" against the new nullable field, which is worse than either. Both go.
    """
    apps.get_model("economy", "DirectZWork").objects.update(
        ai_rating=None,
        rating_note="rated by an older method that didn't watch the video",
    )


def leave_them_cleared(apps, schema_editor):
    """Reverse is a no-op: the old scores are not recoverable, and would not be
    worth recovering. The field goes back to non-null with its 0 default."""


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0072_game_build_command"),
    ]

    operations = [
        migrations.AddField(
            model_name="directzwork",
            name="craft",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="directzwork",
            name="rating_note",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="directzwork",
            name="ai_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        # After the column can hold NULL, not before.
        migrations.RunPython(clear_the_old_seeds, leave_them_cleared),
    ]
