# Generated by Django 5.2.17 on 2026-08-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0073_directzwork_craft_directzwork_rating_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="coach",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="post",
            name="coach_note",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="post",
            name="coach_rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
