# Generated by Django 5.2.17 on 2026-08-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0073_directzwork_craft_directzwork_rating_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("add_funds", "Add funds"),
                    ("purchase", "Purchase"),
                    ("royalty", "Royalty"),
                    ("reward", "Reward"),
                    ("spend", "Spend"),
                    ("intelligence", "Intelligence royalty"),
                ],
                max_length=16,
            ),
        ),
    ]
