# Generated by Django 5.2.17 on 2026-08-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0075_questclaim"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="missing_since",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
