# Generated by Django 5.2.17 on 2026-08-28 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Renumbered from 0076 onto the head that main actually carries: two
        # other PRs landed 0076 and 0077 while this branch was open, and two
        # leaves in the graph is a migrate that refuses to run. This one only
        # creates new tables, so where it sits in the order changes nothing.
        ("economy", "0077_key_voice_use"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                ("title", models.CharField(blank=True, default="", max_length=160)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("great", "Great 😄"),
                            ("good", "Good 🙂"),
                            ("ok", "OK 😐"),
                            ("low", "Low 🙁"),
                            ("rough", "Rough 😣"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                ("weather", models.CharField(blank=True, default="", max_length=40)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("people", models.JSONField(blank=True, default=list)),
                (
                    "place_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("place_lat", models.FloatField(blank=True, null=True)),
                ("place_lng", models.FloatField(blank=True, null=True)),
                ("place_exact", models.BooleanField(default=False)),
                ("items", models.JSONField(blank=True, default=list)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Just me"),
                            ("restricted", "Members only"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries",
                        to="economy.post",
                    ),
                ),
            ],
            options={
                "ordering": ("-day", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="JournalMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="economy.journalentry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_mentions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-notified_at",),
            },
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["author", "day"], name="economy_jou_author__fefe43_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="journalmention",
            unique_together={("entry", "user")},
        ),
    ]
