# Generated by Django 5.2.17 on 2026-09-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0078_journalentry_journalmention"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunnelEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("landing_view", "Landing page viewed"),
                            ("try_view", "Trial take screen opened"),
                            ("try_scored", "Trial take scored"),
                            ("register_view", "Register screen opened"),
                            ("register_success", "Account created"),
                            ("login_success", "Logged in"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("anon_id", models.CharField(db_index=True, max_length=64)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
