# Generated by Django 5.2.17 on 2026-09-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0079_funnelevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funnelevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("landing_view", "Landing page viewed"),
                    ("try_view", "Trial take screen opened"),
                    ("try_scored", "Trial take scored"),
                    ("try_shared", "Trial score shared"),
                    ("register_view", "Register screen opened"),
                    ("register_success", "Account created"),
                    ("login_success", "Logged in"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
