# Generated by Django 5.2.17 on 2026-09-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0080_alter_funnelevent_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="voice_emoji",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="voice_explicit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="voice_slang",
            field=models.BooleanField(default=True),
        ),
    ]
