# Generated by Django 5.2.17 on 2026-09-04 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0082_specz_is_authored_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ringing", "Ringing"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                            ("declined", "Declined"),
                            ("missed", "Missed"),
                        ],
                        default="ringing",
                        max_length=10,
                    ),
                ),
                ("rate_cents_per_min", models.PositiveIntegerField(default=0)),
                ("held_cents", models.PositiveIntegerField(default=0)),
                ("charged_cents", models.PositiveIntegerField(default=0)),
                ("billed_seconds", models.PositiveIntegerField(default=0)),
                ("offer_sdp", models.TextField(blank=True, default="")),
                ("answer_sdp", models.TextField(blank=True, default="")),
                ("caller_ice", models.JSONField(blank=True, default=list)),
                ("callee_ice", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("end_reason", models.CharField(blank=True, default="", max_length=32)),
                (
                    "callee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "caller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["callee", "status"],
                        name="economy_cal_callee__22766d_idx",
                    ),
                    models.Index(
                        fields=["caller", "status"],
                        name="economy_cal_caller__48adf1_idx",
                    ),
                ],
            },
        ),
    ]
