# Generated by Django 5.2.17 on 2026-09-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0083_callz"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="sound_overrides",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="profile",
            name="sound_pack",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
