# Generated by Django 5.2.17 on 2026-09-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0084_soundz"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="open_in",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
