# Generated by Django 5.2.17 on 2026-09-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0085_post_embeds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="embeds",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
