# Generated by Django 5.2.17 on 2026-09-05 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0085_transaction_open_in"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.CharField(db_index=True, max_length=64)),
                ("anon_key", models.CharField(blank=True, default="", max_length=32)),
                ("day", models.DateField()),
                ("started_at", models.DateTimeField()),
                ("last_beat_at", models.DateTimeField()),
                ("beats", models.PositiveIntegerField(default=1)),
                (
                    "viewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["target", "last_beat_at"],
                        name="economy_vie_target_39b3c6_idx",
                    ),
                    models.Index(
                        fields=["target", "started_at"],
                        name="economy_vie_target_7e34ba_idx",
                    ),
                ],
                "unique_together": {("target", "viewer", "anon_key", "day")},
            },
        ),
    ]
