# Generated by Django 5.2.17 on 2026-09-06 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0086_alter_post_embeds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SoundCloudEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_id", models.CharField(max_length=100)),
                ("track_url", models.CharField(max_length=500)),
                (
                    "track_title",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("repost", "Repost"),
                            ("comment", "Comment"),
                        ],
                        max_length=12,
                    ),
                ),
                ("rewarded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soundcloud_engagements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "kind", "-created_at"],
                        name="economy_sou_user_id_50b5b2_idx",
                    )
                ],
                "unique_together": {("user", "track_id", "kind")},
            },
        ),
    ]
