# Generated by Django 5.2.17 on 2026-09-06 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0087_soundcloudengagement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, default="", max_length=500)),
                (
                    "specializations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of instruments/styles coached",
                    ),
                ),
                ("students_count", models.IntegerField(db_index=True, default=0)),
                ("takes_rated", models.IntegerField(default=0)),
                ("avg_rating_quality", models.FloatField(blank=True, null=True)),
                ("referral_spinaz_earned", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referral_code",
                    models.CharField(
                        blank=True, default="", max_length=20, unique=True
                    ),
                ),
                ("takes_submitted", models.IntegerField(default=0)),
                ("takes_rated", models.IntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-joined_at",),
                "unique_together": {("student", "coach")},
            },
        ),
        migrations.CreateModel(
            name="TakeRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pitch_accuracy",
                    models.IntegerField(blank=True, help_text="0-100%", null=True),
                ),
                (
                    "timing_accuracy",
                    models.IntegerField(blank=True, help_text="0-100%", null=True),
                ),
                (
                    "tone_quality",
                    models.IntegerField(blank=True, help_text="0-100%", null=True),
                ),
                ("notes", models.TextField(blank=True, default="", max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="take_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "take",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_ratings",
                        to="economy.post",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "unique_together": {("coach", "take")},
            },
        ),
    ]
