# Generated by Django 5.2.17 on 2026-09-06 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0090_dupeflag_sharedaddress_accountip"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoicePrefs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("style", models.CharField(default="corey", max_length=12)),
                ("emoji", models.CharField(default="heavy", max_length=8)),
                ("depth", models.CharField(default="normal", max_length=8)),
                ("slang", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
