# Generated by Django 5.2.17 on 2026-09-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0091_voiceprefs"),
    ]

    operations = [
        migrations.AddField(
            model_name="directzwork",
            name="copyright",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="directzwork",
            name="copyright_claim",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="directzwork",
            name="copyright_state",
            field=models.CharField(db_index=True, default="unscanned", max_length=12),
        ),
    ]
