# Generated by Django 5.2.17 on 2026-09-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0092_directzwork_copyright_directzwork_copyright_claim_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="app_key",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="transaction",
            name="target",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
    ]
