# Generated by Django 5.2.17 on 2026-09-07 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0094_drumpattern_patternshare_practicesession_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("habit", "HabitZ"),
                    ("code", "CodeZ"),
                    ("path", "PathZ"),
                    ("mistake", "MistakeZ"),
                    ("coach", "CoachZ Feedback"),
                ],
                db_index=True,
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="observationconsent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("habit", "HabitZ"),
                    ("code", "CodeZ"),
                    ("path", "PathZ"),
                    ("mistake", "MistakeZ"),
                    ("coach", "CoachZ Feedback"),
                ],
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="DrillTake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weak_note", models.CharField(max_length=10)),
                ("original_frequency", models.FloatField()),
                ("original_cents_off", models.IntegerField()),
                (
                    "accuracy_percent",
                    models.IntegerField(
                        default=0, help_text="0-100 accuracy % when ending the drill"
                    ),
                ),
                ("duration_seconds", models.IntegerField(default=0)),
                (
                    "final_frequency",
                    models.FloatField(
                        blank=True, help_text="Last detected frequency in Hz", null=True
                    ),
                ),
                (
                    "final_cents_off",
                    models.IntegerField(
                        blank=True,
                        help_text="Deviation from target at end of drill",
                        null=True,
                    ),
                ),
                (
                    "improvement",
                    models.IntegerField(
                        blank=True,
                        help_text="Cents closer to target: original - final",
                        null=True,
                    ),
                ),
                (
                    "key_context",
                    models.CharField(
                        blank=True,
                        help_text="Musical key (e.g., A major)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "bpm_context",
                    models.IntegerField(
                        blank=True, help_text="Song BPM from coach context", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drill_takes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
