# Generated by Django 5.2.17 on 2026-09-07 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "economy",
            "0095_alter_observation_kind_alter_observationconsent_kind_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TakeAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detected_notes",
                    models.JSONField(
                        default=list, help_text="[{note, freq, cents_off, timestamp}]"
                    ),
                ),
                (
                    "weak_notes",
                    models.JSONField(
                        default=list,
                        help_text="[{note, freq, cents_off}] notes consistently off",
                    ),
                ),
                (
                    "timing_issues",
                    models.JSONField(
                        default=dict, help_text="{rushing_count, dragging_count}"
                    ),
                ),
                (
                    "overall_pitch_accuracy",
                    models.IntegerField(
                        blank=True,
                        help_text="0-100% of sung frames in tune; null if nothing was measurable",
                        null=True,
                    ),
                ),
                (
                    "analysis_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="economy.upload",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
