# Generated by Django 5.2.17 on 2026-09-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0101_userpreferences"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterField(
            model_name="habit",
            name="app_key",
            field=models.CharField(
                default="singz", help_text="singz, rapz, etc", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="last_completed",
            field=models.DateTimeField(
                blank=True, help_text="Last time user marked it done", null=True
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="title",
            field=models.CharField(
                help_text="e.g., 'Daily vocal warmup'", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("follow", "Follow"),
                    ("rate", "Rating"),
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("join", "Restricted join"),
                    ("pay", "Payment"),
                    ("message", "Message"),
                    ("system", "System"),
                    ("habit_reminder", "Habit reminder"),
                ],
                default="system",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="seeking",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
