# Generated by Django 5.2.17 on 2026-09-09 22:26

from django.db import migrations


def check_premium_posts_over_limit(apps, schema_editor):
    """Check for Premium posts with 15+ embeds before the limit is enforced."""
    Post = apps.get_model("economy", "Post")
    Membership = apps.get_model("economy", "Membership")

    premium_posts_over_limit = []

    # Find all Premium posts with 15+ embeds
    for post in Post.objects.filter(author__membership__tier="premium"):
        embeds_count = len(post.embeds or [])
        if embeds_count >= 15:
            premium_posts_over_limit.append({
                "post_id": post.id,
                "author": post.author.username,
                "embeds_count": embeds_count,
                "title": post.title[:50],
            })

    if premium_posts_over_limit:
        print(f"\n⚠️  Found {len(premium_posts_over_limit)} Premium posts with 15+ embeds:")
        for p in premium_posts_over_limit:
            print(f"  Post {p['post_id']} by @{p['author']}: {p['embeds_count']} embeds — \"{p['title']}\"")
        print("  These posts will be capped at 15 embeds on display.\n")
    else:
        print("\n✓ No Premium posts with 15+ embeds found. Limit change is safe.\n")


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0102_add_habit_reminder_notification"),
    ]

    operations = [
        migrations.RunPython(check_premium_posts_over_limit, migrations.RunPython.noop),
    ]
