# Generated by Django 5.2.17 on 2026-09-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0103_cap_premium_embeds_at_15"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="battle_eligible_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="collab_eligible_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("restricted", "Restricted"),
                    ("private", "Private"),
                ],
                default="restricted",
                max_length=12,
            ),
        ),
    ]
