# Generated by Django 5.2.17 on 2026-09-10 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0104_post_battle_eligible_at_post_collab_eligible_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("add_funds", "Add funds"),
                    ("purchase", "Purchase"),
                    ("royalty", "Royalty"),
                    ("reward", "Reward"),
                    ("spend", "Spend"),
                    ("intelligence", "Intelligence royalty"),
                    ("transfer", "Transfer"),
                    ("payout", "Payout to bank"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="PayoutAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("stripe", "Stripe")], default="stripe", max_length=12
                    ),
                ),
                (
                    "account_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("payouts_enabled", models.BooleanField(default=False)),
                ("requirements", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_cents", models.PositiveIntegerField()),
                ("fee_cents", models.PositiveIntegerField(default=0)),
                ("net_cents", models.PositiveIntegerField()),
                ("provider", models.CharField(default="stripe", max_length=12)),
                (
                    "provider_ref",
                    models.CharField(
                        blank=True, default=None, max_length=120, null=True, unique=True
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("paid", "Paid"),
                            ("failed", "Failed — returned to wallet"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=12,
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="economy_pay_user_id_2e3156_idx",
                    )
                ],
            },
        ),
    ]
