# Generated by Django 5.2.17 on 2026-09-10 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0106_signbonus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="prompt_walls",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wallet",
            name="prompt_walls_since",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="OfferDismissal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_key", models.CharField(max_length=48)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_dismissals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "offer_key")},
            },
        ),
    ]
