# Generated by Django 5.2.17 on 2026-09-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0107_offer_dismissal_and_prompt_walls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funnelevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("landing_view", "Landing page viewed"),
                    ("try_view", "Trial take screen opened"),
                    ("try_record", "Trial recorder started"),
                    ("try_mic_denied", "Trial mic refused"),
                    ("try_attach", "Trial file attached"),
                    ("try_send", "Trial take sent to the coach"),
                    ("try_failed", "Trial take came back with no score"),
                    ("try_scored", "Trial take scored"),
                    ("try_shared", "Trial score shared"),
                    ("register_view", "Register screen opened"),
                    ("register_success", "Account created"),
                    ("login_success", "Logged in"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
