# Generated by Django 5.2.17 on 2026-09-11 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0108_membergroup_membergroupmember"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("bio", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabelContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Artist Agreement", max_length=120)),
                ("terms_text", models.TextField()),
                (
                    "advance_display",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offered", "Offered"),
                            ("signed", "Signed"),
                            ("declined", "Declined"),
                        ],
                        default="offered",
                        max_length=12,
                    ),
                ),
                (
                    "owner_signed_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("owner_signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "artist_signed_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("artist_signed_at", models.DateTimeField(blank=True, null=True)),
                ("doc_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="economy.label",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
