# Generated by Django 5.2.17 on 2026-09-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0108_alter_funnelevent_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="personality",
            field=models.CharField(blank=True, db_index=True, default="", max_length=4),
        ),
    ]
