# Generated by Django 5.2.17 on 2026-09-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0109_label_labelcontract"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="stripe_verification_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="stripe_verification_session_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
