# Generated by Django 5.2.17 on 2026-09-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0109_profile_personality"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="personality_detail",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
