# Generated by Django 5.2.17 on 2026-09-11 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0111_membergroup_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(db_index=True)),
                ("duration_minutes", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="WorkoutSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_name", models.CharField(max_length=80)),
                (
                    "muscle_group",
                    models.CharField(
                        choices=[
                            ("chest", "Chest"),
                            ("back", "Back"),
                            ("shoulders", "Shoulders"),
                            ("biceps", "Biceps"),
                            ("triceps", "Triceps"),
                            ("forearms", "Forearms"),
                            ("quads", "Quads"),
                            ("hamstrings", "Hamstrings"),
                            ("glutes", "Glutes"),
                            ("calves", "Calves"),
                            ("core", "Core"),
                            ("cardio", "Cardio"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        choices=[
                            ("barbell", "Barbell"),
                            ("dumbbell", "Dumbbell"),
                            ("machine", "Machine"),
                            ("cable", "Cable"),
                            ("bodyweight", "Bodyweight"),
                            ("bands", "Resistance bands"),
                            ("kettlebell", "Kettlebell"),
                            ("cardio", "Cardio machine"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        choices=[
                            ("push", "Push"),
                            ("pull", "Pull"),
                            ("squat", "Squat"),
                            ("hinge", "Hinge"),
                            ("lunge", "Lunge"),
                            ("carry", "Carry"),
                            ("core", "Core"),
                            ("cardio", "Cardio"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("reps", models.IntegerField(default=0)),
                ("weight_lbs", models.FloatField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.IntegerField(
                        default=0,
                        help_text="Cardio/carry work measured in time, not reps",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="economy.workoutsession",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.AddIndex(
            model_name="workoutsession",
            index=models.Index(
                fields=["user", "-started_at"], name="economy_wor_user_id_c69555_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutset",
            index=models.Index(
                fields=["muscle_group"], name="economy_wor_muscle__fc7556_idx"
            ),
        ),
    ]
