# Generated by Django 5.2.17 on 2026-09-13 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0111_alter_funnelevent_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LilithPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(db_index=True, max_length=24)),
                ("spinaz", models.PositiveIntegerField(default=0)),
                ("energy", models.PositiveIntegerField(default=0)),
                ("xp", models.PositiveIntegerField(default=0)),
                (
                    "ref",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lilith_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LilithRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("app_key", models.CharField(blank=True, default="", max_length=32)),
                ("target", models.CharField(blank=True, default="", max_length=64)),
                ("streak", models.PositiveIntegerField(default=0)),
                ("longest", models.PositiveIntegerField(default=0)),
                ("last_done", models.DateField(blank=True, null=True)),
                ("paid_milestones", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lilith_routines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-streak", "title"),
            },
        ),
        migrations.CreateModel(
            name="LilithSponsorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("graduated_at", models.DateTimeField(blank=True, null=True)),
                ("paid", models.BooleanField(default=False)),
                ("refused", models.CharField(blank=True, default="", max_length=64)),
                (
                    "helper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lilith_sponsored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "newcomer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lilith_sponsors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "unique_together": {("helper", "newcomer")},
            },
        ),
        migrations.CreateModel(
            name="LilithTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("quick", "Quick Tap ⚡"),
                            ("standard", "Standard Task ✅"),
                            ("deep", "Deep Work 🧠"),
                            ("boss", "Boss Task 👑"),
                            ("auto", "Auto Task 🤖"),
                            ("statz", "StatZ Task 🌟"),
                        ],
                        default="standard",
                        max_length=10,
                    ),
                ),
                (
                    "bucket",
                    models.CharField(
                        choices=[
                            ("inbox", "Inbox 📥"),
                            ("today", "Today ‼️"),
                            ("upcoming", "Upcoming ❗"),
                            ("anytime", "Anytime 👐🏼"),
                            ("someday", "Someday ❓"),
                            ("logbook", "Logbook 🧾"),
                        ],
                        db_index=True,
                        default="inbox",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("self", "Typed by the member"),
                            ("platform", "Points at a real action"),
                            ("auto", "Made by an automation rule"),
                        ],
                        default="self",
                        max_length=10,
                    ),
                ),
                ("app_key", models.CharField(blank=True, default="", max_length=32)),
                ("target", models.CharField(blank=True, default="", max_length=64)),
                ("due", models.DateTimeField(blank=True, null=True)),
                ("done_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "routine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="economy.lilithroutine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lilith_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("done_at", "due", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["user", "bucket", "done_at"],
                        name="economy_lil_user_id_724ca0_idx",
                    )
                ],
            },
        ),
    ]
