# Generated by Django 5.2.17 on 2026-09-14 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0112_lilithpayout_lilithroutine_lilithsponsorship_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_key", models.CharField(db_index=True, max_length=32)),
                (
                    "confirmed_range",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                ("goal_range", models.CharField(blank=True, default="", max_length=24)),
                (
                    "fatigue_sensitivity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Takes a lot before I feel it"),
                            ("normal", "Normal"),
                            ("high", "I feel it quickly"),
                        ],
                        default="",
                        max_length=8,
                    ),
                ),
                ("bpm_low", models.PositiveIntegerField(blank=True, null=True)),
                ("bpm_high", models.PositiveIntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrument_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "app_key")},
            },
        ),
        migrations.CreateModel(
            name="TakeScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_key", models.CharField(db_index=True, max_length=32)),
                ("scores", models.JSONField(blank=True, default=dict)),
                ("overall", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "weakest",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=24
                    ),
                ),
                ("difficulty", models.CharField(blank=True, default="", max_length=16)),
                ("genre", models.CharField(blank=True, default="", max_length=60)),
                ("target", models.CharField(blank=True, default="", max_length=60)),
                ("style", models.CharField(blank=True, default="", max_length=60)),
                (
                    "range_class",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                ("low_note", models.CharField(blank=True, default="", max_length=8)),
                ("high_note", models.CharField(blank=True, default="", max_length=8)),
                ("source", models.CharField(blank=True, default="", max_length=16)),
                ("ref", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="take_scores",
                        to="economy.upload",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="take_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "app_key", "-created_at"],
                        name="economy_tak_user_id_01a51f_idx",
                    )
                ],
            },
        ),
    ]
