# Generated by Django 5.2.17 on 2026-09-14 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0113_instrumentprofile_takescore"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="socialcomment",
            name="karma_energy",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="socialcomment",
            name="karma_settled_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="EngagementPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(db_index=True, max_length=24)),
                ("energy", models.PositiveIntegerField(default=0)),
                ("spinaz", models.PositiveIntegerField(default=0)),
                (
                    "ref",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "kind", "-created_at"],
                        name="economy_eng_user_id_935720_idx",
                    )
                ],
                "unique_together": {("user", "kind", "ref")},
            },
        ),
    ]
