# Generated by Django 5.2.17 on 2026-09-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0114_socialcomment_karma_energy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentprofile",
            name="goal_high",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="instrumentprofile",
            name="goal_low",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="instrumentprofile",
            name="top_styles",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
