# Generated by Django 5.2.17 on 2026-09-14 20:02

from django.db import migrations, models


def partners_become_custom(apps, schema_editor):
    """PartnerZ is derived from finished collabs now, so a stored partners row
    no longer has a kind to render as.

    CONVERTED rather than deleted. The feature shipped one commit ago so there
    is almost certainly nothing here — but "almost certainly" is not a reason
    to drop somebody's list, and a curated group is exactly the kind of small
    thing whose disappearance nobody can explain afterwards. It becomes a
    Custom list with its own name, which is what it was: a list they made.
    """
    Group = apps.get_model("economy", "Group")
    Group.objects.filter(kind="partners").update(
        kind="custom", title="Partners (your old list)")


def custom_stays_custom(apps, schema_editor):
    """Nothing to undo — a converted list is indistinguishable from one the
    member made themselves, and guessing which is which would be worse than
    leaving them."""


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0116_group_groupmember_and_more"),
    ]

    operations = [
        migrations.RunPython(partners_become_custom, custom_stays_custom),
        migrations.AlterField(
            model_name="group",
            name="kind",
            field=models.CharField(
                choices=[("custom", "Custom")], default="custom", max_length=16
            ),
        ),
    ]
