# Generated by Django 5.2.17 on 2026-09-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0119_backfill_partnerships"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name_public",
            field=models.BooleanField(default=False),
        ),
    ]
