# Generated by Django 5.2.17 on 2026-09-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0121_profile_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="emoji",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
