# Generated by Django 5.2.17 on 2026-09-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0122_group_emoji"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialtake",
            name="anon_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="funnelevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("landing_view", "Landing page viewed"),
                    ("try_view", "Trial take screen opened"),
                    ("try_blocked", "Trial door was shut"),
                    ("try_record", "Trial recorder started"),
                    ("try_mic_denied", "Trial mic refused"),
                    ("try_attach", "Trial file attached"),
                    ("try_send", "Trial take sent to the coach"),
                    ("try_failed", "Trial take came back with no score"),
                    ("try_scored", "Trial take scored"),
                    ("quiz_view", "PersonalitieZ test opened"),
                    ("quiz_done", "PersonalitieZ test finished"),
                    ("try_shared", "Trial score shared"),
                    ("register_view", "Register screen opened"),
                    ("register_success", "Account created"),
                    ("login_success", "Logged in"),
                    ("onboard_habit", "Onboarding habit created"),
                    ("onboard_skip", "Onboarding habit skipped"),
                    ("onboard_prefs", "Onboarding preferences confirmed"),
                    ("oauth_linked", "OAuth linked after login"),
                    ("oauth_link_fail", "OAuth link failed after login"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
