# Generated by Django 5.2.17 on 2026-09-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0123_trialtake_anon_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialtake",
            name="scored",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
