# Generated by Django 5.2.17 on 2026-09-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0126_backfill_collab_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="religion",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=32
            ),
        ),
    ]
