# Generated by Django 5.2.17 on 2026-09-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0127_profile_religion"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="languages",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
