# Generated by Django 5.2.17 on 2026-09-23 22:32

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0128_profile_languages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Membership: Online status, activity indicator, activity timestamp
        migrations.AddField(
            model_name='membership',
            name='online_status',
            field=models.CharField(
                choices=[('online', 'Online'), ('idle', 'Idle'), ('away', 'Away'), ('offline', 'Offline')],
                default='offline',
                max_length=16,
                db_index=True,
            ),
        ),
        migrations.AddField(
            model_name='membership',
            name='current_activity',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', 'None'),
                    ('listening', 'Listening'),
                    ('composing', 'Composing'),
                    ('recording', 'Recording'),
                    ('battling', 'In Battle'),
                    ('collaborating', 'Collaborating'),
                ],
                default='',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='membership',
            name='last_activity_at',
            field=models.DateTimeField(null=True, blank=True, db_index=True),
        ),

        # Message: Read receipts with timestamps, delivered timestamp
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='delivered_at',
            field=models.DateTimeField(null=True, blank=True),
        ),

        # ActivityEvent: Timeline feed for social events
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(
                    choices=[
                        ('follow', 'Started following'),
                        ('like', 'Liked post'),
                        ('rate', 'Rated take'),
                        ('collab_invite', 'Invited to collaborate'),
                        ('collab_accept', 'Accepted collaboration'),
                        ('collab_complete', 'Completed collaboration'),
                        ('battle_invite', 'Invited to battle'),
                        ('battle_enter', 'Entered battle'),
                        ('battle_win', 'Won battle'),
                        ('post_publish', 'Published post'),
                        ('take_score', 'Got coached'),
                        ('profile_view', 'Viewed your profile'),
                    ],
                    max_length=20,
                    db_index=True,
                )),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events_received', to=settings.AUTH_USER_MODEL)),
                ('app_key', models.CharField(blank=True, default='', max_length=20)),
                ('target', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read', models.BooleanField(default=False, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [
                    models.Index(fields=['subject', 'read', '-created_at'], name='economy_act_subject_read_idx'),
                ],
            },
        ),
    ]
