# Generated by Django 5.2.17 on 2026-09-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0132_dawvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodiezroutine",
            name="bucket",
            field=models.CharField(
                choices=[
                    ("inbox", "Inbox 📥"),
                    ("today", "Today 💪"),
                    ("upcoming", "Upcoming 📅"),
                    ("anytime", "Anytime 🏋️"),
                    ("someday", "Someday 🧠"),
                    ("trash", "Trash 🚮"),
                ],
                db_index=True,
                default="inbox",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="bodiezroutine",
            name="scheduled_for",
            field=models.DateField(blank=True, null=True),
        ),
    ]
