# Generated by Django 5.2.17 on 2026-09-21 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0134_bodiezgoal_bodiezweightlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BodieZRecoveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("soreness", models.PositiveSmallIntegerField()),
                ("sleep_quality", models.PositiveSmallIntegerField()),
                ("fatigue", models.PositiveSmallIntegerField()),
                ("notes", models.CharField(blank=True, default="", max_length=280)),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bodiez_recovery_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-logged_at",),
            },
        ),
    ]
