# Generated by Django 5.2.17 on 2026-09-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0135_bodiezrecoverylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodiezexercise",
            name="demo_url",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="bodiezexercise",
            name="equipment",
            field=models.CharField(
                choices=[
                    ("bodyweight", "Bodyweight"),
                    ("dumbbell", "Dumbbell"),
                    ("barbell", "Barbell"),
                    ("ez_bar", "EZ Bar"),
                    ("kettlebell", "Kettlebell"),
                    ("machine", "Machine"),
                    ("cable", "Cable / Pulley"),
                    ("band", "Band"),
                ],
                max_length=12,
            ),
        ),
    ]
