# Generated by Django 5.2.17 on 2026-09-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0142_bodiez_legs_demo_videos"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodiezroutine",
            name="day_tag",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mon", "Mon"),
                    ("tue", "Tue"),
                    ("wed", "Wed"),
                    ("thu", "Thu"),
                    ("fri", "Fri"),
                    ("sat", "Sat"),
                    ("sun", "Sun"),
                    ("any", "Any"),
                ],
                default="",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="bodiezroutine",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
