# Generated by Django 5.2.17 on 2026-09-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0129_add_engagement_features"),
        ("economy", "0146_bodiez_machine_bench_and_more_demos"),
    ]

    operations = []
