# Generated by Django 5.2.17 on 2026-09-28 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0147_add_post_monetization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveIntegerField(default=5)),
                ("text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="coachprofile",
            name="featured_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="coachprofile",
            name="lesson_rate_cents_per_min",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="coachprofile",
            name="verified_lesson_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name="coachprofile",
            index=models.Index(
                fields=["-verified_lesson_count"], name="economy_coa_verifie_3b6088_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coachprofile",
            index=models.Index(
                fields=["featured_until"], name="economy_coa_feature_a5739e_idx"
            ),
        ),
        migrations.AddField(
            model_name="coachreview",
            name="coach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coach_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coachreview",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="coachreview",
            index=models.Index(
                fields=["coach", "-created_at"], name="economy_coa_coach_i_43ea28_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coachreview",
            unique_together={("coach", "student")},
        ),
    ]
