# Generated by Django 5.2.17 on 2026-09-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0147_merge_20260924_1527"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodiezexercise",
            name="position",
            field=models.CharField(
                choices=[
                    ("standing", "Standing"),
                    ("seated", "Seated"),
                    ("lying", "Lying"),
                    ("mixed", "Can be modified"),
                ],
                default="standing",
                max_length=10,
            ),
        ),
    ]
