# Generated by Django 5.2.17 on 2026-09-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0148_add_bodiez_exercise_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="accessibility_preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="profile",
            name="disabilities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="relationship_status",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="relationships",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
