# Generated by Django 5.2.17 on 2026-09-28 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0149_add_gap3_improvement_loop"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BeatZ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("genre", models.CharField(blank=True, default="", max_length=50)),
                ("tempo_bpm", models.PositiveIntegerField(blank=True, null=True)),
                ("price_cents", models.PositiveIntegerField(default=500)),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("exclusive", "Exclusive"),
                            ("nonexclusive", "Non-exclusive"),
                        ],
                        default="nonexclusive",
                        max_length=20,
                    ),
                ),
                ("quantity_available", models.PositiveIntegerField(default=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audio_upload",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beat_audio",
                        to="economy.upload",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beats_produced",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BeatPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("exclusive", "Exclusive"),
                            ("nonexclusive", "Non-exclusive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price_cents", models.PositiveIntegerField()),
                ("developer_cut_cents", models.PositiveIntegerField(default=0)),
                ("producer_payout_cents", models.PositiveIntegerField(default=0)),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beat_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "beat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="economy.beatz",
                    ),
                ),
            ],
            options={
                "ordering": ("-purchased_at",),
            },
        ),
        migrations.CreateModel(
            name="BeatUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usage_kind",
                    models.CharField(
                        choices=[
                            ("personal", "Personal/Demo"),
                            ("youtube", "YouTube"),
                            ("streaming", "Streaming (Spotify, Apple Music, etc)"),
                            ("commercial", "Commercial/Sync"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.TextField(blank=True, default="")),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beat_usages",
                        to="economy.post",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="economy.beatpurchase",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beat_usages",
                        to="economy.upload",
                    ),
                ),
            ],
            options={
                "ordering": ("-reported_at",),
                "indexes": [
                    models.Index(
                        fields=["purchase", "-reported_at"],
                        name="economy_bea_purchas_322e92_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="beatz",
            index=models.Index(
                fields=["producer", "-created_at"],
                name="economy_bea_produce_d1030c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="beatz",
            index=models.Index(fields=["genre"], name="economy_bea_genre_d55b88_idx"),
        ),
        migrations.AddIndex(
            model_name="beatpurchase",
            index=models.Index(
                fields=["buyer", "-purchased_at"], name="economy_bea_buyer_i_0bb19b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="beatpurchase",
            index=models.Index(
                fields=["beat", "-purchased_at"], name="economy_bea_beat_id_4fb0f3_idx"
            ),
        ),
    ]
