# Generated by Django 5.2.17 on 2026-09-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0149_add_disability_and_relationship_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name='bodiezexercise',
            name='requires_arms',
            field=models.BooleanField(default=True, help_text='Exercise requires or uses arms'),
        ),
        migrations.AddField(
            model_name='bodiezexercise',
            name='requires_legs',
            field=models.BooleanField(default=True, help_text='Exercise requires or uses legs'),
        ),
    ]
