# Generated by Django 5.2.17 on 2026-09-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0151_add_sonday_board_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodiezset",
            name="rest_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
