# Generated by Django 5.2.17 on 2026-09-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0152_bodiezset_rest_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodiezroutine",
            name="goal",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
