# Generated by Django 5.2.17 on 2026-10-02 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0154_sentencework"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntelligenceUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_kind", models.CharField(max_length=16)),
                ("source_id", models.PositiveIntegerField()),
                ("target_kind", models.CharField(max_length=12)),
                ("target_id", models.PositiveIntegerField()),
                ("text", models.TextField(blank=True, default="")),
                ("royalty_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                ("paid_cents", models.PositiveIntegerField(default=0)),
                ("paid_spinaz", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intelligence_uses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target_kind", "target_id"],
                        name="economy_int_target__d830fe_idx",
                    )
                ],
                "unique_together": {
                    ("source_kind", "source_id", "target_kind", "target_id")
                },
            },
        ),
    ]
