# Generated by Django 5.2.17 on 2026-10-02 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0155_intelligenceuse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentalWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(blank=True, default="", max_length=60)),
                ("instruments", models.JSONField(default=list)),
                ("bpm", models.PositiveSmallIntegerField()),
                ("key", models.CharField(max_length=12)),
                ("bars", models.PositiveSmallIntegerField(default=4)),
                ("brief", models.TextField(blank=True, default="")),
                ("tracks", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrumental_works",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
