# Generated by Django 5.2.17 on 2026-10-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0158_viewsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="partnered",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="collabdeal",
            name="partnered",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("follow", "Follow"),
                    ("rate", "Rating"),
                    ("like", "Like"),
                    ("partnerz", "PartnerZ"),
                    ("comment", "Comment"),
                    ("join", "Restricted join"),
                    ("pay", "Payment"),
                    ("message", "Message"),
                    ("system", "System"),
                    ("habit_reminder", "Habit reminder"),
                ],
                default="system",
                max_length=16,
            ),
        ),
    ]
