# Generated by Django 5.2.17 on 2026-10-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0159_partnered_marks"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewsession",
            name="dev",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="viewsession",
            name="src",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
    ]
