# Generated by Django 5.2.17 on 2026-10-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0161_videowork"),
    ]

    operations = [
        migrations.CreateModel(
            name="Horoscope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sign", models.CharField(max_length=12)),
                ("day", models.DateField()),
                ("reading", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("sign", "day")},
            },
        ),
    ]
