# Generated by Django 5.2.17 on 2026-10-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0162_horoscope"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="owner_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
