# Generated by Django 5.2.17 on 2026-10-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0163_membership_owner_pinned"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="horoscope",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="horoscope",
            name="level",
            field=models.CharField(default="basic", max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name="horoscope",
            unique_together={("sign", "day", "level")},
        ),
    ]
