# Generated by Django 5.2.17 on 2026-10-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0164_horoscope_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuebooking",
            name="spinaz_held",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="venuebooking",
            name="spinaz_settled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="venueevent",
            name="category",
            field=models.CharField(
                choices=[("music", "Music"), ("fitness", "Fitness / lifting")],
                db_index=True,
                default="music",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="venueevent",
            name="spinaz_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="venueevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("performance", "Performance — the visitor pays the host"),
                    ("session", "Session — the host pays the visitor"),
                    ("free", "Free — nobody pays"),
                    ("spinaz", "SpinaZ — the visitor pays the host a flat 🍥 entry"),
                ],
                db_index=True,
                max_length=12,
            ),
        ),
    ]
