# Generated by Django 5.2.17 on 2026-10-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0165_venuez_fitness_and_spinaz"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodiezset",
            name="converted_from_lb",
            field=models.BooleanField(default=False),
        ),
    ]
