# Generated by Django 5.2.17 on 2026-10-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0166_bodiezset_converted_from_lb"),
    ]

    operations = [
        migrations.AddField(
            model_name="venueevent",
            name="gates",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
