# Generated by Django 5.2.17 on 2026-10-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0167_venueevent_gates"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="gates",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
