# Generated by Django 5.2.17 on 2026-10-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0168_range_gates_posts_and_lessons"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="contact_gates",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
