# Generated by Django 5.2.17 on 2026-10-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0169_profile_contact_gates"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="rating_carry",
            field=models.FloatField(default=0),
        ),
    ]
