# Generated by Django 5.2.17 on 2026-10-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0170_wallet_rating_carry"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cover_url",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="profile",
            name="gear",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="genres",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="headline",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="influences",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="label",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="pinned_post_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="pronouns",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="profile",
            name="timezone",
            field=models.CharField(blank=True, default="", max_length=48),
        ),
    ]
