# Generated by Django 5.2.17 on 2026-10-03 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0171_profile_popular_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=32, unique=True)),
                ("app_key", models.CharField(max_length=32)),
                ("score", models.PositiveSmallIntegerField()),
                ("verdict", models.CharField(blank=True, default="", max_length=400)),
                ("genre", models.CharField(blank=True, default="", max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
