# Generated by Django 5.2.17 on 2026-10-03 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0172_score_share"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="campaign_email",
            field=models.BooleanField(
                default=False, help_text="Email me campaigns from people I follow"
            ),
        ),
        migrations.CreateModel(
            name="ParcelCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=160)),
                ("body", models.TextField(blank=True, default="")),
                ("audience", models.CharField(max_length=16)),
                ("channels", models.JSONField(blank=True, default=list)),
                ("recipients", models.PositiveIntegerField(default=0)),
                ("messaged", models.PositiveIntegerField(default=0)),
                ("emailed", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="economy.post",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcel_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
