# Generated by Django 5.2.17 on 2026-10-04 23:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0174_push_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funnelevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("landing_view", "Landing page viewed"),
                    ("try_view", "Trial take screen opened"),
                    ("try_blocked", "Trial door was shut"),
                    ("try_record", "Trial recorder started"),
                    ("try_mic_denied", "Trial mic refused"),
                    ("try_attach", "Trial file attached"),
                    ("try_send", "Trial take sent to the coach"),
                    ("try_failed", "Trial take came back with no score"),
                    ("try_scored", "Trial take scored"),
                    ("quiz_view", "PersonalitieZ test opened"),
                    ("quiz_done", "PersonalitieZ test finished"),
                    ("try_shared", "Trial score shared"),
                    ("try_email", "Trial score emailed for a retake"),
                    ("register_view", "Register screen opened"),
                    ("register_success", "Account created"),
                    ("login_success", "Logged in"),
                    ("onboard_habit", "Onboarding habit created"),
                    ("onboard_skip", "Onboarding habit skipped"),
                    ("onboard_prefs", "Onboarding preferences confirmed"),
                    ("oauth_linked", "OAuth linked after login"),
                    ("oauth_link_fail", "OAuth link failed after login"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RetakeReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("app_key", models.CharField(default="singz", max_length=32)),
                (
                    "anon_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("stage", models.PositiveSmallIntegerField(default=0)),
                ("armed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("failures", models.PositiveSmallIntegerField(default=0)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stop_reason",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trial_take",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminders",
                        to="economy.trialtake",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
