# Generated by Django 6.0.9 on 2026-10-07 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0175_retake_reminders"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bodiezexercise",
            name="needs_arms",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bodiezexercise",
            name="needs_legs",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bodiezexercise",
            name="positions",
            field=models.CharField(default="standing", max_length=40),
        ),
        migrations.CreateModel(
            name="BodieZAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seated_or_lying_only", models.BooleanField(default=False)),
                ("arms_ok", models.BooleanField(default=True)),
                ("legs_ok", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bodiez_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
