# Generated by Django 6.0.9 on 2026-10-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0177_bodiez_access_tags_and_new_exercises"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunnelExclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anon_id", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
