# Generated by Django 6.0.9 on 2026-10-08 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0178_bodiez_rdl_is_dumbbell"),
        ("economy", "0179_funnel_register_fail"),
    ]

    operations = []
