# Generated by Django 6.0.9 on 2026-10-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0182_bodiez_step_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodiezsession",
            name="backfilled",
            field=models.BooleanField(default=False),
        ),
    ]
