# Generated by Django 6.0.9 on 2026-10-08 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0186_bodiez_one_sided"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bodiezexercise",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bodiez_custom_exercises",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bodiezexercise",
            name="name",
            field=models.CharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name="bodiezexercise",
            constraint=models.UniqueConstraint(
                condition=models.Q(("created_by__isnull", True)),
                fields=("name",),
                name="bodiez_exercise_library_name_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="bodiezexercise",
            constraint=models.UniqueConstraint(
                condition=models.Q(("created_by__isnull", False)),
                fields=("created_by", "name"),
                name="bodiez_exercise_custom_name_uniq",
            ),
        ),
    ]
