# Generated by Django 6.0.9 on 2026-10-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0190_bodiez_jefit_gap_exercises"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodiezroutine",
            name="source",
            field=models.CharField(
                choices=[
                    ("member", "Yours"),
                    ("coach", "Coach-built"),
                    ("session", "From a workout"),
                    ("trial", "From the trial"),
                ],
                default="member",
                max_length=10,
            ),
        ),
    ]
